from pathlib import Path

html_path=Path('conversation.html')
js_path=Path('conversation.js')
html=html_path.read_text(encoding='utf-8')
js=js_path.read_text(encoding='utf-8')

# CSS for proper ruby/furigana spacing and mobile legibility.
css='.jp ruby{ruby-position:over}.jp rt{font-family:-apple-system,BlinkMacSystemFont,"Yu Gothic UI","Noto Sans JP",sans-serif;font-size:.48em;line-height:1;color:#596579;font-weight:700}.jp ruby{margin:0 .02em}'
if css not in html:
    marker='@media(max-width:760px)'
    if marker not in html: raise SystemExit('CSS insertion marker not found')
    html=html.replace(marker,css+'\n'+marker,1)

# Add exactly one learner-facing furigana toggle, enabled by default.
toggle='<label class="switch"><input id="showFurigana" type="checkbox" checked> 漢字顯示ふりがな</label>'
while html.count(toggle)>1:
    first=html.find(toggle)
    second=html.find(toggle,first+len(toggle))
    html=html[:second]+html[second+len(toggle):]
if toggle not in html:
    old='<label class="switch"><input id="showZh" type="checkbox" checked> 顯示繁體中文</label>'
    if old not in html: raise SystemExit('Furigana toggle insertion marker not found')
    html=html.replace(old,toggle+'\n'+old,1)

# Load generated readings after the complete 61-scene database has been assembled.
for oldver in ['./conversation-furigana.js?v=20260815v1','./conversation-furigana.js?v=20260815v2']:
    html=html.replace(oldver,'./conversation-furigana.js?v=20260815v2')
script='<script src="./conversation-furigana.js?v=20260815v2"></script>'
if script not in html:
    marker='<script src="./conversation-world-expansion.js?v=20260815v1"></script>'
    if marker not in html: raise SystemExit('World expansion script marker not found')
    html=html.replace(marker,marker+'\n'+script,1)

# Cache-bust rendering logic where an older URL is still present.
for oldver in ['./conversation.js?v=20260814v2','./conversation.js?v=20260815v2']:
    html=html.replace(oldver,'./conversation.js?v=20260815v3')

# Safe HTML is generated by our build pipeline; all fallbacks remain escaped.
esc_line="function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]))}"
jp_func="function jpHtml(s){const x=window.CONVERSATION_FURIGANA?.[String(s??'')];return $('#showFurigana')?.checked&&x?x:esc(s)}"
if jp_func not in js:
    if esc_line not in js: raise SystemExit('esc function marker not found')
    js=js.replace(esc_line,esc_line+'\n'+jp_func,1)

old_render="${hide?'聽完後按「顯示日文」':esc(l.jp)}"
new_render="${hide?'聽完後按「顯示日文」':jpHtml(l.jp)}"
if old_render in js:
    js=js.replace(old_render,new_render,1)
elif new_render not in js:
    raise SystemExit('Japanese render marker not found')

listener="document.addEventListener('change',e=>{if(e.target?.id==='showFurigana')render()});"
if listener not in js:
    marker="if(S.mode==='dictation')updateDictPrompt();\n}"
    if marker not in js: raise SystemExit('render function end marker not found')
    js=js.replace(marker,marker+'\n'+listener,1)

html_path.write_text(html,encoding='utf-8')
js_path.write_text(js,encoding='utf-8')
print('Conversation furigana UI patched without duplicate controls.')
