// Load the curated supplement and validated repo-hosted expansion before the game initializes.
document.write('<script src="./advanced_words_curated.js?v=20260826v2"><\/script>');
// Legacy curated rows stored kanji/display and kana reading in reversed object fields.
// Normalize them before any exact-key teacher overlay or audit-derived runtime logic runs.
document.write('<script src="./data/advanced_words_field_normalizer.js?v=20260826v1"><\/script>');
// Full-database teacher-audit outputs. Exact manual secondary cross-checks remain layered after it.
document.write('<script src="./data/vocab_core_verified.js?v=20260826v5teacher"><\/script>');
document.write('<script src="./data/vocab_external_crosscheck.js?v=20260826v4jlpt"><\/script>');
document.write('<script src="./core_vocab_fetch_patch.js?v=20260826v2"><\/script>');
// Teacher-audited 22k advanced bundle. Cache token is pinned so browsers cannot reuse
// the old world-distribution or frequency-heavy classification.
document.write('<script src="./data/advanced_vocab.js?v=20260826v10teacher"><\/script>');
// Exact-only Stage 2 safeguards. Broad JLPT reassignment is generated in CI, never here.
document.write('<script src="./data/vocab_stage2_level_overrides.js?v=20260826v3exact"><\/script>');
// Strict surface-form completion layers. Their historical level labels are no longer
// authoritative: the generated teacher runtime overlay below reconciles every exact key.
document.write('<script src="./data/coverage_deferred_manual.js?v=20260821v1"><\/script>');
document.write('<script src="./data/coverage_sourcecheck_manual.js?v=20260821v1"><\/script>');
document.write('<script src="./data/coverage_postreview_manual.js?v=20260821v1"><\/script>');
// Validate that the generated v5 teacher bundle, not an obsolete browser-built cache, is active.
document.write('<script src="./large_vocab_loader.js?v=20260826v5teacher"><\/script>');
// Direct-reviewed common words that must remain present even if an upstream deck changes.
document.write('<script src="./data/vocab_common_fixups.js?v=20260826v3"><\/script>');
// FINAL JLPT authority for additive runtime vocabulary. This file is generated by CI
// from the full teacher audit and is deliberately loaded after every supplement/fixup.
document.write('<script src="./data/vocab_teacher_runtime_overlay.js?v=20260826v2lineage"><\/script>');
// Hosted audio no longer needs the old 400 MB browser model cache or service worker.
document.write('<script src="./wordaudio-hosted-cleanup.js?v=20260827v1"><\/script>');
// Hosted-audio delta overlay. It waits for wordaudio-multivoice.js before installing,
// so non-audio vocabulary pages simply ignore it.
document.write('<script src="./wordaudio-delta-voices.js?v=20260827v2"><\/script>');

// Pronunciation fix: always speak the explicit kana reading shown in the answer sheet.
// This prevents browser TTS from guessing an incorrect reading from kanji such as 白粉（おしろい）.
document.addEventListener("click",function(event){
  const button=event.target.closest?.("#speak");
  if(!button)return;
  const reading=document.querySelector("#aReading")?.textContent?.trim();
  if(!reading||!("speechSynthesis" in window))return;
  event.preventDefault();
  event.stopImmediatePropagation();
  speechSynthesis.cancel();
  const utterance=new SpeechSynthesisUtterance(reading);
  utterance.lang="ja-JP";
  utterance.rate=.85;
  const japaneseVoice=speechSynthesis.getVoices().find(v=>/^ja(?:-|_)/i.test(v.lang));
  if(japaneseVoice)utterance.voice=japaneseVoice;
  speechSynthesis.speak(utterance);
},true);