(()=>{"use strict";
const V="large-vocab-20260813-v5",M=`jpquiz_${V}_meta`,P=`jpquiz_${V}_chunk_`,SZ=650000;
const U={core:["https://raw.githubusercontent.com/5mdld/anki-jlpt-decks/main/deck-source/notes.csv","https://cdn.jsdelivr.net/gh/5mdld/anki-jlpt-decks@main/deck-source/notes.csv"],jld:["https://raw.githubusercontent.com/jkindrix/japanese-language-data/main/data/core/words.json","https://cdn.jsdelivr.net/gh/jkindrix/japanese-language-data@main/data/core/words.json"],freq:["https://raw.githubusercontent.com/jkindrix/japanese-language-data/main/data/enrichment/frequency-subtitles.json","https://cdn.jsdelivr.net/gh/jkindrix/japanese-language-data@main/data/enrichment/frequency-subtitles.json"],thes:["https://raw.githubusercontent.com/lxl66566/Japanese-Chinese-thesaurus/main/final.json","https://cdn.jsdelivr.net/gh/lxl66566/Japanese-Chinese-thesaurus@main/final.json"],wiki:["https://raw.githubusercontent.com/open-dict-data/wikidict-zh/master/data/ja-zh_wiki.txt","https://cdn.jsdelivr.net/gh/open-dict-data/wikidict-zh@master/data/ja-zh_wiki.txt"],kaikki:"https://kaikki.org/zhwiktionary/%E6%97%A5%E8%AF%AD/kaikki.org-dictionary-%E6%97%A5%E8%AF%AD.jsonl",opencc:"https://cdn.jsdelivr.net/npm/opencc-js@1.4.1/dist/umd/full.js"};
const K=/^[ぁ-ゖァ-ヺー・ヽヾゝゞ]+$/u,J=/^[ぁ-ゖァ-ヺ\u3400-\u9fff々〆ヵヶー・]+$/u,C=/[\u3400-\u9fff々]/u,BAD=new Set(["arch","obs","rare","dated","person","place","company","product","organization","surname","given","n-pr","X","sk","sK","rk","rK","ok","oK"]);
const $=s=>document.querySelector(s),status=s=>{const e=$("#advStatus");if(e)e.textContent=s},lock=on=>{const b=$("#start");if(b&&on)b.disabled=true};
function clean(s){const d=document.createElement("div");d.innerHTML=String(s||"").replace(/\[sound:[^\]]+\]/gi," ").replace(/<br\s*\/?>/gi," ");return(d.textContent||"").replace(/\s+/g," ").trim()}
async function first(a,t="text"){let e;for(const u of a){try{const r=await fetch(u,{cache:"no-cache"});if(!r.ok)throw Error(`HTTP ${r.status}`);return t==="json"?await r.json():await r.text()}catch(x){e=x}}throw e||Error("download failed")}
async function converter(){if(window.OpenCC?.Converter)return OpenCC.Converter({from:"cn",to:"hk"});await new Promise((ok,no)=>{const s=document.createElement("script");s.src=U.opencc;s.onload=ok;s.onerror=()=>no(Error("OpenCC 載入失敗"));document.head.appendChild(s)});return OpenCC.Converter({from:"cn",to:"hk"})}
function csv(t){const h=(t.split(/\r?\n/,1)[0]||"").trim().toLowerCase(),d=h==="#separator:comma"?",":h==="#separator:semicolon"?";":"\t",z=[];let r=[],f="",q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'){if(t[i+1]==='"'){f+='"';i++}else q=false}else f+=c}else if(c==='"')q=true;else if(c===d){r.push(f);f=""}else if(c==='\n'){r.push(f);z.push(r);r=[];f=""}else if(c!=='\r')f+=c}if(f||r.length){r.push(f);z.push(r)}return z}
function fur(x,w){let s=clean(x||w).replace(/\s+/g,"").replace(/[\u3400-\u9fff々〆ヵヶ]+\[([^\]]+)\]/g,"$1").replace(/\[([^\]]+)\]/g,"$1");return K.test(s)?s:K.test(w||"")?w:""}
function coreKeys(t){const s=new Set;for(let r of csv(t)){if(!r.length||String(r[0]||"").trim().startsWith("#"))continue;if(r.length===41)r=r.slice(1);if(r.length===39)r=["",...r];if(r.length!==40)continue;const w=clean(r[3]).replace(/\s/g,""),rd=fur(r[6],w);if(w&&rd)s.add(`${rd}|${w}`)}return s}
function choose(w){const senses=(w.sense||[]).filter(s=>![...(s.misc||[]),...(s.partOfSpeech||[])].some(x=>BAD.has(x)));if(!senses.length)return null;const ks=(w.kanji||[]).filter(x=>!(x.tags||[]).some(t=>BAD.has(t))),rs=(w.kana||[]).filter(x=>!(x.tags||[]).some(t=>BAD.has(t)));if(!rs.length)return null;const k=ks.find(x=>x.common)||ks[0],written=k?.text||"";let rr=rs.filter(x=>{const a=x.appliesToKanji||[];return !written||!a.length||a.includes("*")||a.includes(written)});if(!rr.length)rr=rs;const rd=String((rr.find(x=>x.common)||rr[0])?.text||"").trim(),display=written||rd;if(!K.test(rd)||!J.test(display)||display.length>22)return null;const forms=[];for(const x of [display,...ks.map(x=>x.text),...rs.map(x=>x.text)])if(x&&J.test(x)&&!forms.includes(x))forms.push(x);const p=senses.flatMap(s=>s.partOfSpeech||[]);let pos="other";if(p.some(x=>/^v|^vs/.test(x)))pos="verb";else if(p.some(x=>/^adj/.test(x)))pos="adj";else if(p.some(x=>/^adv/.test(x)))pos="adv";else if(p.some(x=>/^n/.test(x)))pos="noun";else if(p.includes("conj"))pos="conj";else if(p.includes("prt"))pos="particle";return{w,rd,display,kanji:C.test(display)?display:"",forms:forms.slice(0,8),pos}}
function meaning(x,cv){x=clean(x).replace(/^\([^)]{1,30}\)\s*/,"").replace(/^(名詞|名词|動詞|动词|形容詞|形容词|副詞|副词|名|動|动)\s*/,"").trim();x=cv(x).replace(/\s+/g," ").trim();if(!x||x.length>90||!C.test(x)||/[＋+\[\]{}]/.test(x)||/表示.{0,6}(句型|文法|語法)|前接|後接/.test(x))return"";return x.split(/[。；;]/).map(s=>s.trim()).filter(Boolean).slice(0,2).join("；").slice(0,75)}
function level(e,f){const x=e.w.jlpt_waller;if(/^N[1-5]$/.test(x||""))return x;let r=999999;for(const a of e.forms)r=Math.min(r,f.get(`${a}|${e.rd}`)||f.get(a)||999999);return r<=1200?"N5":r<=3000?"N4":r<=5500?"N3":r<=8000?"N2":"N1"}
function tlevel(k,r,f){const n=Math.min(f.get(`${k}|${r}`)||999999,f.get(k)||999999);return n<=1200?"N5":n<=3000?"N4":n<=5500?"N3":n<=8000?"N2":/^[ァ-ヺー]+$/.test(k)&&k.length<=8?"N3":C.test(k)&&k.length<=2?"N2":"N1"}
function add(m,x,score,core,cur){if(!x?.meaning||!K.test(x.reading)||!J.test(x.display))return;const k=`${x.reading}|${x.display}`;if(core.has(k)||cur.has(k))return;const o=m.get(k);if(!o||score>o.score)m.set(k,{...x,score})}
function clear(){try{const m=JSON.parse(localStorage.getItem(M)||"null");for(let i=0;i<(m?.chunks||30);i++)localStorage.removeItem(P+i);localStorage.removeItem(M)}catch{}}
function save(a,meta){const s=JSON.stringify(a),n=Math.ceil(s.length/SZ);clear();try{for(let i=0;i<n;i++)localStorage.setItem(P+i,s.slice(i*SZ,(i+1)*SZ));localStorage.setItem(M,JSON.stringify({...meta,version:V,chunks:n,count:a.length}));return true}catch(e){clear();return false}}
window.JPVocabLarge={V,M,P,U,K,J,C,status,lock,clean,first,converter,coreKeys,choose,meaning,level,tlevel,add,save};
})();
