(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VOCAB_URLS=["https://raw.githubusercontent.com/5mdld/anki-jlpt-decks/main/deck-source/notes.csv","https://cdn.jsdelivr.net/gh/5mdld/anki-jlpt-decks@main/deck-source/notes.csv"];
const GRAMMAR_FILES={N5:"grammar_ja_N5_full_alphabetical_0001.json",N4:"grammar_ja_N4_full_alphabetical_0001.json",N3:"grammar_ja_N3_full_alphabetical_0001.json",N2:"grammar_ja_N2_full_alphabetical_0001.json",N1:"grammar_ja_N1_full_alphabetical_0001.json"};
const GRAMMAR_BASES=["https://raw.githubusercontent.com/tristcoil/hanabira.org-japanese-content/main/grammar_json/","https://cdn.jsdelivr.net/gh/tristcoil/hanabira.org-japanese-content@main/grammar_json/"];
const CFG={
N1:{pass:100,sections:[{key:"main",title:"言語知識（文字・語彙・文法）・読解",min:110,plan:{vocab:20,grammar:14,reading:16}},{key:"listening",title:"聴解",min:55,plan:{listening:22}}]},
N2:{pass:90,sections:[{key:"main",title:"言語知識（文字・語彙・文法）・読解",min:105,plan:{vocab:20,grammar:14,reading:15}},{key:"listening",title:"聴解",min:50,plan:{listening:22}}]},
N3:{pass:95,sections:[{key:"vocab",title:"言語知識（文字・語彙）",min:30,plan:{vocab:22}},{key:"grammarReading",title:"言語知識（文法）・読解",min:70,plan:{grammar:14,reading:14}},{key:"listening",title:"聴解",min:40,plan:{listening:20}}]},
N4:{pass:90,sections:[{key:"vocab",title:"言語知識（文字・語彙）",min:25,plan:{vocab:20}},{key:"grammarReading",title:"言語知識（文法）・読解",min:55,plan:{grammar:12,reading:12}},{key:"listening",title:"聴解",min:35,plan:{listening:18}}]},
N5:{pass:80,sections:[{key:"vocab",title:"言語知識（文字・語彙）",min:20,plan:{vocab:18}},{key:"grammarReading",title:"言語知識（文法）・読解",min:40,plan:{grammar:10,reading:10}},{key:"listening",title:"聴解",min:30,plan:{listening:16}}]}
};
const FALLBACK_VOCAB={
N5:[["学生","がくせい","學生"],["先生","せんせい","老師"],["電車","でんしゃ","電車"],["学校","がっこう","學校"],["時間","じかん","時間"],["食べる","たべる","吃"],["飲む","のむ","喝"],["大きい","おおきい","大的"]],
N4:[["約束","やくそく","約定"],["準備","じゅんび","準備"],["説明","せつめい","說明"],["計画","けいかく","計畫"],["続ける","つづける","繼續"],["必要","ひつよう","必要"],["間に合う","まにあう","趕得上"],["急に","きゅうに","突然"]],
N3:[["経験","けいけん","經驗"],["環境","かんきょう","環境"],["影響","えいきょう","影響"],["確認","かくにん","確認"],["結果","けっか","結果"],["結局","けっきょく","結果、終究"],["かなり","かなり","相當"],["わざわざ","わざわざ","特意"]],
N2:[["改善","かいぜん","改善"],["効率","こうりつ","效率"],["傾向","けいこう","傾向"],["対応","たいおう","應對"],["実施","じっし","實施"],["あいにく","あいにく","不巧"],["とうとう","とうとう","終於"],["むしろ","むしろ","反而"]],
N1:[["把握","はあく","掌握"],["蓄積","ちくせき","累積"],["推測","すいそく","推測"],["促進","そくしん","促進"],["見通し","みとおし","展望"],["おおむね","おおむね","大致"],["もっぱら","もっぱら","專門、主要"],["あながち","あながち","未必、未見得"]]
};
const FALLBACK_GRAMMAR={
N5:[["まだ～ていません","宿題はまだ終わっていません。"],["～たり～たりする","日曜日は本を読んだり、音楽を聞いたりします。"],["～から","雨が降っていますから、傘を持っていきます。"],["～たい","週末に映画を見たいです。"]],
N4:[["～ながら","音楽を聞きながら勉強します。"],["～そうだ","空が暗いので、雨が降りそうです。"],["～たことがある","京都へ行ったことがあります。"],["～ようになる","毎日練習して、日本語が話せるようになりました。"]],
N3:[["～ことになっている","この建物では靴を脱ぐことになっています。"],["～うちに","日本にいるうちに、北海道へ行きたいです。"],["～ばかり","弟はゲームをしてばかりいます。"],["～ように","忘れないように、メモしてください。"]],
N2:[["～にもかかわらず","雨にもかかわらず、多くの人が集まりました。"],["～に違いない","電気がついているから、彼は家にいるに違いない。"],["～わけではない","甘い物が全部嫌いなわけではありません。"],["～ものの","買ったものの、まだ一度も使っていません。"]],
N1:[["～に至るまで","子どもから大人に至るまで、多くの人が参加した。"],["～を皮切りに","東京公演を皮切りに、全国ツアーが始まる。"],["～とはいえ","春とはいえ、朝晩はまだ寒い。"],["～に堪えない","皆様のご支援には感謝に堪えません。"]]
};
const SPECIAL={
N1:[
{type:"言い換え類義",q:"『おおむね』と意味が最も近いものはどれですか。",c:["だいたい","まったく","突然","わざと"],a:0,e:"「おおむね」は「だいたい・概して」に近い意味です。"},
{type:"用法",q:"『もっぱら』の使い方として最もよいものはどれですか。",c:["最近は、もっぱら在宅で仕事をしている。","雨がもっぱら降り始めた。","駅までにもっぱら歩いた。","彼は昨日にもっぱら来た。"],a:0,e:"「もっぱら」は、主として・ほとんどそれだけ、という意味です。"},
{type:"用法",q:"『あながち』の使い方として最もよいものはどれですか。",c:["その予想もあながち間違いとは言えない。","あながち駅へ急いでください。","昨日あながち映画を見た。","机の上にあながち置いた。"],a:0,e:"「あながち～ない」で、必ずしも～ない／一概に～ない、の意味になります。"}],
N2:[
{type:"語形成",q:"『再び利用すること』を表す語として最もよいものはどれですか。",c:["再利用","未利用","利用的","利用性"],a:0,e:"「再＋利用」で「再利用」となります。"},
{type:"言い換え類義",q:"『とうとう』と意味が最も近いものはどれですか。",c:["ついに","たまたま","めったに","あらかじめ"],a:0,e:"「とうとう」は、長い経過の末に「ついに」という意味です。"},
{type:"用法",q:"『あいにく』の使い方として最もよいものはどれですか。",c:["あいにく、その日は予定が入っています。","あいにく毎日運動します。","本をあいにく三冊買いました。","駅はあいにく五分です。"],a:0,e:"「あいにく」は、都合が悪い・残念ながら、という場面で使います。"}],
N3:[
{type:"言い換え類義",q:"『かなり』と意味が最も近いものはどれですか。",c:["相当","少しも","必ず","たまたま"],a:0,e:"「かなり」は「相当・だいぶ」に近い意味です。"},
{type:"用法",q:"『わざわざ』の使い方として最もよいものはどれですか。",c:["わざわざ駅まで迎えに来てくれた。","雨がわざわざ降っている。","三時にわざわざ寝た。","机がわざわざ大きい。"],a:0,e:"「わざわざ」は、そのために特別に行動することを表します。"},
{type:"言い換え類義",q:"『結局』と意味が最も近いものはどれですか。",c:["最終的に","最初から","ときどき","急に"],a:0,e:"「結局」は、いろいろあった結果として最終的に、という意味です。"}],
N4:[
{type:"言い換え類義",q:"『急に』と意味が最も近いものはどれですか。",c:["突然","ゆっくり","必ず","だいたい"],a:0,e:"「急に」は「突然」に近い意味です。"},
{type:"用法",q:"『間に合う』の使い方として最もよいものはどれですか。",c:["急げば九時の電車に間に合います。","この料理は塩に間に合います。","本を間に合って読みました。","昨日は友達に間に合いました。"],a:0,e:"「間に合う」は、決められた時間までに到着・完成できる意味です。"},
{type:"言い換え類義",q:"『たいてい』と意味が最も近いものはどれですか。",c:["ほとんどの場合","一度も","突然","特別に"],a:0,e:"「たいてい」は、多くの場合・普通は、という意味です。"}],
N5:[
{type:"言い換え類義",q:"『すぐ』と意味が最も近いものはどれですか。",c:["すぐに","ゆっくり","ときどき","まだ"],a:0,e:"「すぐ」は、時間を置かずに、という意味です。"},
{type:"言い換え類義",q:"『たくさん』と意味が最も近いものはどれですか。",c:["多く","少し","一つ","半分"],a:0,e:"「たくさん」は、量や数が多いことを表します。"}]
};
const QUICK_RESPONSE={
N5:[
["すみません、今何時ですか。",["三時です。","三人です。","三冊です。"],0],["このペンを使ってもいいですか。",["はい、どうぞ。","いいえ、ペンです。","昨日でした。"],0],["明日、学校へ行きますか。",["はい、行きます。","いいえ、学校です。","はい、昨日です。"],0]],
N4:[
["窓を閉めましょうか。",["はい、お願いします。","窓が三つです。","もう閉めませんでした。"],0],["会議は何時からですか。",["二時からです。","会議室でした。","二時間をします。"],0],["駅までどうやって行きますか。",["バスで行きます。","駅を行きます。","十分が行きます。"],0]],
N3:[
["この資料、今日中にできますか。",["はい、夕方までには終わります。","いいえ、資料を見ました。","今日は資料でした。"],0],["田中さん、まだ来ていませんか。",["ええ、まだのようです。","はい、昨日来ません。","田中さんが来ますか。"],0],["この辺に銀行はありませんか。",["角を曲がったところにあります。","銀行を持っていません。","昨日は休みました。"],0]],
N2:[
["締め切り、来週に延ばせないでしょうか。",["担当者に確認してみます。","来週は七日あります。","締め切りを書きました。"],0],["この案について、どう思いますか。",["もう少し検討する必要があると思います。","昨日その案を読みません。","会議室は二階です。"],0],["先方への連絡は済みましたか。",["はい、先ほどメールを送りました。","いいえ、先方は会社です。","連絡は電話でしたか。"],0]],
N1:[
["この方針、現場には浸透しているんでしょうか。",["少なくとも全員に理解されているとは言い難いですね。","現場は一階にあります。","方針を昨日印刷しました。"],0],["交渉は難航しているそうですね。",["ええ、双方の条件にまだ隔たりがあります。","はい、交渉は会議室です。","いいえ、昨日は雨でした。"],0],["今回の結果をどう受け止めていますか。",["課題は残りましたが、一定の成果はあったと考えています。","結果は三枚あります。","昨日受け取りましたか。"],0]]
};
let vocab=[],grammar={N1:[],N2:[],N3:[],N4:[],N5:[]},voicevoxIndex={items:{}},loadDone=false,state=null,timerId=null,activeAudio=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;","\"":"&quot;","'":"&#39;"}[c]))}
function strip(s){const d=document.createElement("div");d.innerHTML=String(s??"").replace(/\[sound:[^\]]+\]/gi," ").replace(/<br\s*\/?>/gi,"；");return(d.textContent||"").replace(/\s+/g," ").trim()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function sample(a,n){return shuffle(a).slice(0,n)}
function kana(s){return!!s&&/^[ぁ-ゖァ-ヺー・ヽヾゝゞ]+$/.test(String(s).replace(/\s+/g,""))}
function hasKanji(s){return/[\u3400-\u4DBF\u4E00-\u9FFF々〆ヵヶ]/.test(s||"")}
function currentLevel(){return $("input[name=level]:checked")?.value||"N3"}
function currentMode(){return $("input[name=mode]:checked")?.value||"full"}
const F=["Notetype","Deck","NoteID","VocabKanji","VocabPitch","VocabPoS","VocabFurigana","VocabDefSC","VocabDefTC","VocabPlus","VocabAudio","SentType1","SentKanji1","SentFurigana1","SentDefSC1","SentDefTC1","SentAudio1","SentType2","SentKanji2","SentFurigana2","SentDefSC2","SentDefTC2","SentAudio2","SentType3","SentKanji3","SentFurigana3","SentDefSC3","SentDefTC3","SentAudio3","SentType4","SentKanji4","SentFurigana4","SentDefSC4","SentDefTC4","SentAudio4","Sort","Alt1","Alt2","Tags"];
function parseCSV(text){const first=(text.split(/\r?\n/,1)[0]||"").trim().toLowerCase(),del=first==="#separator:comma"?",":first==="#separator:semicolon"?";":"\t",rows=[];let row=[],field="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){field+='"';i++}else q=false}else field+=c}else{if(c==='"')q=true;else if(c===del){row.push(field);field=""}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=""}else if(c!=='\r')field+=c}}if(field.length||row.length){row.push(field);rows.push(row)}return rows}
function fields(r){r=[...r];if(r.length===F.length+1)r=r.slice(1);if(r.length===F.length)return Object.fromEntries(F.map((n,i)=>[n,r[i]??""]));if(r.length===F.length-1){const o={Notetype:""};for(let i=1;i<F.length;i++)o[F[i]]=r[i-1]??"";return o}return null}
function reading(furi,word){let s=String(furi||word||"").trim().replace(/<rt[^>]*>(.*?)<\/rt>/gi,"$1").replace(/<rp[^>]*>.*?<\/rp>/gi,"").replace(/<ruby[^>]*>|<\/ruby>/gi,"");s=s.replace(/[\u3400-\u4DBF\u4E00-\u9FFF々〆ヵヶ]+\[([^\]]+)\]/g,"$1").replace(/\[([^\]]+)\]/g,"$1");s=strip(s).replace(/\s+/g,"");if(kana(s))return s;const w=strip(word).replace(/\s+/g,"");return kana(w)?w:""}
function rowsToVocab(rows){const out=[];for(const r of rows){if(!r?.length||String(r[0]||"").trim().startsWith("#"))continue;const f=fields(r);if(!f)continue;const word=strip(f.VocabKanji).replace(/\s+/g,""),meaning=strip(f.VocabDefTC),m=`${f.Deck||""} ${f.Tags||""}`.match(/(?:^|[^A-Za-z0-9])N([1-5])(?=$|[^0-9])/i);if(!word||!meaning||!m)continue;const rd=reading(f.VocabFurigana||word,word);if(!kana(rd))continue;const level=`N${m[1]}`,sentence=strip(f.SentKanji1||"");out.push({id:`v-${f.NoteID||`${level}-${word}-${rd}`}`,level,word,reading:rd,meaning,sentence,pos:strip(f.VocabPoS||"")})}const seen=new Set;return out.filter(x=>{const k=`${x.level}|${x.word}|${x.reading}`;if(seen.has(k))return false;seen.add(k);return true})}
async function fetchVocab(){let err;for(const u of VOCAB_URLS){try{const r=await fetch(u,{cache:"default"});if(!r.ok)throw Error(`HTTP ${r.status}`);const rows=rowsToVocab(parseCSV(await r.text()));if(rows.length<1000)throw Error("詞彙資料不足");return rows}catch(e){err=e}}console.warn(err);return Object.entries(FALLBACK_VOCAB).flatMap(([level,rows],i)=>rows.map((x,j)=>({id:`fbv-${level}-${j}`,level,word:x[0],reading:x[1],meaning:x[2],sentence:"",pos:""})))}
function cleanGrammarTitle(t){return String(t||"").replace(/\s*\([^()]*\)\s*$/,"").trim()}
function grammarExpr(t){let s=cleanGrammarTitle(t).replace(/[～〜]/g,"").trim();s=s.split(/[／/]| or /i)[0].trim();return s.length>=2&&s.length<=18?s:""}
async function fetchGrammarLevel(level){let last;for(const b of GRAMMAR_BASES){try{const r=await fetch(b+GRAMMAR_FILES[level],{cache:"default"});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d))throw Error("格式錯誤");const out=[];d.forEach((p,pi)=>(p.examples||[]).forEach((e,ei)=>{const jp=String(e.jp||"").trim();if(jp.length<5||jp.length>130)return;out.push({id:`g-${level}-${pi}-${ei}`,level,jp,title:cleanGrammarTitle(p.title),expr:grammarExpr(p.title)})}));if(!out.length)throw Error("沒有例句");return out}catch(e){last=e}}console.warn(last);return (FALLBACK_GRAMMAR[level]||[]).map((x,i)=>({id:`fbg-${level}-${i}`,level,title:x[0],expr:grammarExpr(x[0]),jp:x[1]}))}
async function loadAll(){$("#sourceStatus").textContent="正在載入約 10,000 個詞彙及 N1–N5 文法例句…";const [v,...gs]=await Promise.all([fetchVocab(),...["N1","N2","N3","N4","N5"].map(fetchGrammarLevel)]);vocab=v;["N1","N2","N3","N4","N5"].forEach((l,i)=>grammar[l]=gs[i]);try{const r=await fetch("./voicevox-release-index.json",{cache:"no-cache"});if(r.ok){const d=await r.json();if(d?.items)voicevoxIndex=d}}catch{}loadDone=true;const gtotal=Object.values(grammar).reduce((n,a)=>n+a.length,0);$("#readyPill").textContent=`✅ ${vocab.length.toLocaleString()} 詞 · ${gtotal.toLocaleString()} 例句`;$("#sourceStatus").textContent=`✅ Web 題庫已準備：${vocab.length.toLocaleString()} 個詞彙、${gtotal.toLocaleString()} 個文法／例句。`;renderAvailability()}
function renderSchedule(){const l=currentLevel(),mode=currentMode(),cfg=CFG[l];let html='<table class="schedule"><thead><tr><th>科目</th><th>時間</th></tr></thead><tbody>';cfg.sections.forEach(s=>{const m=mode==="quick"?Math.max(5,Math.round(s.min*.12)):s.min;html+=`<tr><td>${esc(s.title)}</td><td><strong>${m} 分</strong>${mode==="quick"?"（快速）":""}</td></tr>`});html+='</tbody></table>';$("#scheduleBox").innerHTML=html}
function renderAvailability(){renderSchedule();if(!loadDone){$("#start").disabled=true;return}const l=currentLevel(),vc=vocab.filter(x=>x.level===l).length,gc=grammar[l].length;$("#availability").textContent=`${l} 可用題源：${vc.toLocaleString()} 個詞彙、${gc.toLocaleString()} 個文法／例句。開始後題目會隨機重新組合。`;$("#start").disabled=vc<8||gc<4}
function similarReading(pool,c){return pool.filter(x=>x.id!==c.id&&x.reading!==c.reading).map(x=>({x,s:Math.abs(x.reading.length-c.reading.length)+(x.reading[0]===c.reading[0]?-.7:0)})).sort((a,b)=>a.s-b.s).map(o=>o.x)}
function similarWord(pool,c){return pool.filter(x=>x.id!==c.id&&x.word!==c.word).map(x=>({x,s:Math.abs(x.word.length-c.word.length)+(x.word[0]===c.word[0]?-.6:0)})).sort((a,b)=>a.s-b.s).map(o=>o.x)}
function qObj(o){return{id:o.id||`q-${Math.random().toString(36).slice(2)}`,type:o.type||"",score:o.score||"language",instruction:o.instruction||"",question:o.question||"",passage:o.passage||"",choices:o.choices||[],answer:o.answer??0,explain:o.explain||"",audioText:o.audioText||"",audioId:o.audioId||"",user:null,flag:false,audioPlayed:false}}
function buildKanji(level,n){const p=vocab.filter(x=>x.level===level&&hasKanji(x.word)),out=[];sample(p,Math.min(n*3,p.length)).forEach(c=>{if(out.length>=n)return;const d=similarReading(p,c).slice(0,8);if(d.length<3)return;const cs=shuffle([c.reading,...sample(d,3).map(x=>x.reading)]),ans=cs.indexOf(c.reading);out.push(qObj({id:`kr-${c.id}`,type:"漢字読み",instruction:"＿＿＿のことばの読み方として最もよいものを、1・2・3・4から一つ選んでください。",question:`【${c.word}】`,choices:cs,answer:ans,explain:`${c.word}（${c.reading}）：${c.meaning}`}))});return out}
function buildOrthography(level,n){if(level==="N1")return[];const p=vocab.filter(x=>x.level===level&&hasKanji(x.word)),out=[];sample(p,Math.min(n*3,p.length)).forEach(c=>{if(out.length>=n)return;const d=similarWord(p,c).slice(0,10);if(d.length<3)return;const cs=shuffle([c.word,...sample(d,3).map(x=>x.word)]),ans=cs.indexOf(c.word);out.push(qObj({id:`or-${c.id}`,type:"表記",instruction:"＿＿＿のことばは、漢字でどう書きますか。最もよいものを一つ選んでください。",question:`【${c.reading}】`,choices:cs,answer:ans,explain:`${c.reading} → ${c.word}：${c.meaning}`}))});return out}
function buildContext(level,n){const p=vocab.filter(x=>x.level===level&&x.sentence&&x.word.length>0&&x.sentence.includes(x.word)),out=[];sample(p,Math.min(n*5,p.length)).forEach(c=>{if(out.length>=n)return;const d=similarWord(p,c).filter(x=>x.word.length<=8).slice(0,14);if(d.length<3)return;const cs=shuffle([c.word,...sample(d,3).map(x=>x.word)]),ans=cs.indexOf(c.word),sent=c.sentence.replace(c.word,"（　　　）");out.push(qObj({id:`cx-${c.id}`,type:"文脈規定",instruction:"（　　　）に入れるのに最もよいものを、一つ選んでください。",question:sent,choices:cs,answer:ans,explain:`正解：${c.word}（${c.reading}）／${c.meaning}`}))});return out}
function specialQs(level,n){return sample(SPECIAL[level]||[],n).map((x,i)=>qObj({id:`sp-${level}-${x.type}-${i}`,type:x.type,instruction:x.type==="用法"?"次のことばの使い方として最もよいものを、一つ選んでください。":"意味が最も近いものを、一つ選んでください。",question:x.q,choices:x.c,answer:x.a,explain:x.e}))}
function buildVocab(level,n){let out=[];const parts=level==="N1"?[8,0,7,5]:[6,5,6,3];out.push(...buildKanji(level,parts[0]),...buildOrthography(level,parts[1]),...buildContext(level,parts[2]),...specialQs(level,parts[3]));if(out.length<n)out.push(...buildKanji(level,n-out.length));return sample(unique(out),n)}
function usableGrammar(level){return grammar[level].filter(x=>x.expr&&x.jp.includes(x.expr))}
function buildGrammarForm(level,n){const p=usableGrammar(level),exprs=[...new Set(p.map(x=>x.expr))],out=[];sample(p,Math.min(n*5,p.length)).forEach(c=>{if(out.length>=n)return;const ds=exprs.filter(x=>x!==c.expr&&Math.abs(x.length-c.expr.length)<=6);if(ds.length<3)return;const cs=shuffle([c.expr,...sample(ds,3)]),ans=cs.indexOf(c.expr),sent=c.jp.replace(c.expr,"（　　　）");out.push(qObj({id:`gf-${c.id}`,type:"文法形式の判断",instruction:"（　　　）に入れるのに最もよいものを、一つ選んでください。",question:sent,choices:cs,answer:ans,explain:`正確文法：${c.title}。原句：${c.jp}`}))});return out}
function splitChunks(s){let t=s.replace(/[。！？!?]$/g,"").trim();if(t.length<12)return null;const marks=[...t.matchAll(/[はがをにでとのへもて、]/g)].map(m=>m.index+1).filter(i=>i>1&&i<t.length-2);const pts=[];for(const target of [t.length*.25,t.length*.5,t.length*.75]){let best=marks.filter(i=>!pts.includes(i)).sort((a,b)=>Math.abs(a-target)-Math.abs(b-target))[0];if(!best)best=Math.round(target);pts.push(best)}pts.sort((a,b)=>a-b);const a=[t.slice(0,pts[0]),t.slice(pts[0],pts[1]),t.slice(pts[1],pts[2]),t.slice(pts[2])].map(x=>x.trim()).filter(Boolean);return a.length===4&&a.every(x=>x.length)?a:null}
function permutations4(a){const arr=[];for(let i=0;i<4;i++)for(let j=0;j<4;j++)if(j!==i)for(let k=0;k<4;k++)if(k!==i&&k!==j){const l=6-i-j-k;arr.push([a[i],a[j],a[k],a[l]])}return arr}
function buildComposition(level,n){const p=grammar[level].filter(x=>x.jp.length>=12&&x.jp.length<=55),out=[];sample(p,Math.min(n*8,p.length)).forEach(c=>{if(out.length>=n)return;const chunks=splitChunks(c.jp);if(!chunks)return;const correct=chunks.join(" "),wrong=sample(permutations4(chunks).filter(x=>x.join(" ")!==correct),3).map(x=>x.join(" "));if(wrong.length<3)return;const cs=shuffle([correct,...wrong]),ans=cs.indexOf(correct);out.push(qObj({id:`gc-${c.id}`,type:"文の組み立て",instruction:"次の文を正しい順序に並べたものを、一つ選んでください。",question:`① ${chunks[0]}　② ${chunks[1]}　③ ${chunks[2]}　④ ${chunks[3]}`,choices:cs,answer:ans,explain:`正しい文：${c.jp}`}))});return out}
function buildTextGrammar(level,n){const p=usableGrammar(level),out=[];for(let i=0;i<n*4&&p.length>3&&out.length<n;i++){const [a,b]=sample(p,2);if(a.id===b.id)continue;const ds=[...new Set(p.map(x=>x.expr).filter(x=>x!==b.expr&&Math.abs(x.length-b.expr.length)<=6))];if(ds.length<3)continue;const passage=`${a.jp}\n${b.jp.replace(b.expr,"（　　　）")}`,cs=shuffle([b.expr,...sample(ds,3)]);out.push(qObj({id:`tg-${a.id}-${b.id}`,type:"文章の文法",instruction:"文章の流れに合うように、（　　　）に入れるのに最もよいものを一つ選んでください。",passage,question:"",choices:cs,answer:cs.indexOf(b.expr),explain:`正確文法：${b.title}。原句：${b.jp}`}))}return out}
function buildGrammar(level,n){const a=Math.ceil(n*.5),b=Math.ceil(n*.25),c=n-a-b;let out=[...buildGrammarForm(level,a),...buildComposition(level,b),...buildTextGrammar(level,c)];if(out.length<n)out.push(...buildGrammarForm(level,n-out.length));return sample(unique(out),n)}
const MUT_GROUPS=[["今日","昨日","明日","今朝"],["今週","先週","来週","再来週"],["今月","先月","来月"],["今年","去年","来年"],["朝","昼","夕方","夜"],["午前","午後"],["右","左","前","後"],["上","下"],["ここ","そこ","あそこ","どこ"],["これ","それ","あれ","どれ"],["まだ","もう"],["いつも","よく","時々","たまに"],["好き","嫌い"],["高い","安い"],["大きい","小さい"],["多い","少ない"],["早い","遅い"],["行きます","来ます","帰ります"],["行く","来る","帰る"],["買います","売ります"],["買う","売る"],["始まります","終わります"],["始まる","終わる"],["増えます","減ります"],["増える","減る"]];
function mutate(s){const out=[];for(const g of MUT_GROUPS){for(const x of g){if(!s.includes(x))continue;for(const y of g)if(y!==x){const z=s.replace(x,y);if(z!==s&&!out.includes(z))out.push(z)}}}const m=s.match(/\d+/);if(m){const n=+m[0];for(const d of [-1,1,2]){const z=s.replace(m[0],String(Math.max(1,n+d)));if(z!==s&&!out.includes(z))out.push(z)}}return out}
function readingTypes(level){return level==="N1"?["短文理解","中文理解","長文理解","統合理解","主題理解"]:level==="N2"?["短文理解","中文理解","統合理解","主題理解"]:level==="N3"?["短文理解","中文理解","長文理解"]:["短文理解","中文理解"]}
function buildReadingContent(level,n){const p=grammar[level].filter(x=>x.jp.length>=12&&x.jp.length<=105&&mutate(x.jp).length>=3),out=[],types=readingTypes(level);for(let i=0;i<n*8&&p.length>5&&out.length<n;i++){const type=types[out.length%types.length],count=type==="短文理解"?2:type==="中文理解"?3:4,rows=sample(p,count);if(rows.length<count)continue;const target=rows[Math.floor(Math.random()*rows.length)],alts=sample(mutate(target.jp),3);if(alts.length<3)continue;let passage;if(type==="統合理解")passage=`【文章A】\n${rows.slice(0,2).map(x=>x.jp).join("\n")}\n\n【文章B】\n${rows.slice(2).map(x=>x.jp).join("\n")}`;else passage=rows.map(x=>x.jp).join("\n");const cs=shuffle([target.jp,...alts]);let instruction="次の文章を読んで、文章の内容と合っているものを一つ選んでください。";if(type==="統合理解")instruction="文章Aと文章Bを読んで、両方の内容から考えて最も適切なものを一つ選んでください。";if(type==="主題理解")instruction="次の文章を読んで、筆者の考えに最も近いものを一つ選んでください。";out.push(qObj({id:`rd-${type}-${rows.map(x=>x.id).join("-")}`,type,score:"reading",instruction,passage,question:"",choices:cs,answer:cs.indexOf(target.jp),explain:`本文に書かれている重要な内容：${target.jp}`}))}return out}
function buildInfo(level,n){const out=[];for(let i=0;i<n;i++){const open=9+(i%2),close=17+(i%3),closed=["月曜日","火曜日","水曜日"][i%3],special=close-2;const passage=`市民図書館からのお知らせ\n開館時間：午前${open}時～午後${close}時\n休館日：毎週${closed}\n土曜日は館内整理のため、午後${special}時に閉館します。`;const correct=`土曜日は午後${special}時まで利用できる。`,cs=shuffle([correct,`土曜日は午後${close}時まで利用できる。`,`毎週${["木曜日","金曜日","日曜日"][i%3]}は休館日だ。`,`毎日午前8時から利用できる。`]);out.push(qObj({id:`info-${level}-${i}-${open}`,type:"情報検索",score:"reading",instruction:"次のお知らせを読んで、正しいものを一つ選んでください。",passage,question:"",choices:cs,answer:cs.indexOf(correct),explain:`土曜日は午後${special}時に閉館すると書かれています。`}))}return out}
function buildReading(level,n){const info=Math.max(2,Math.round(n*.22)),content=n-info;let out=[...buildReadingContent(level,content),...buildInfo(level,info)];if(out.length<n)out.push(...buildInfo(level,n-out.length));return sample(unique(out),n)}
function listeningTypes(level){return level==="N1"||level==="N2"?["課題理解","ポイント理解","概要理解","統合理解"]:level==="N3"?["課題理解","ポイント理解","概要理解"]:["課題理解","ポイント理解"]}
function buildQuickResponse(level,n,type="即時応答"){return sample(QUICK_RESPONSE[level]||[],n).map((x,i)=>qObj({id:`${type==="発話表現"?"ve":"qr"}-${level}-${i}-${Math.random().toString(36).slice(2,5)}`,type,score:"listening",instruction:type==="発話表現"?"場面の説明を聞いて、その場面で最も自然な表現を一つ選んでください。":"話を聞いて、最もよい応答を一つ選んでください。",question:"",choices:x[1],answer:x[2],explain:`音声：${x[0]}　正答：${x[1][x[2]]}`,audioText:x[0]}))}
function buildListeningContent(level,n){const p=grammar[level].filter(x=>x.jp.length>=8&&x.jp.length<=75&&mutate(x.jp).length>=3),out=[],types=listeningTypes(level);for(let i=0;i<n*7&&p.length>5&&out.length<n;i++){const type=types[out.length%types.length];if(type==="統合理解"){const rows=sample(p,2);if(rows.length<2)continue;const target=rows[1],alts=sample(mutate(target.jp),3);if(alts.length<3)continue;const cs=shuffle([target.jp,...alts]);out.push(qObj({id:`lsi-${rows[0].id}-${rows[1].id}`,type,score:"listening",instruction:"二つの内容を続けて聞いて、全体の内容として最もよいものを一つ選んでください。",question:"",choices:cs,answer:cs.indexOf(target.jp),explain:`音声：${rows[0].jp} ${rows[1].jp}`,audioText:`${rows[0].jp} ${rows[1].jp}`}));continue}const c=sample(p,1)[0];if(!c)continue;const alts=sample(mutate(c.jp),3);if(alts.length<3)continue;const cs=shuffle([c.jp,...alts]);const instruction=type==="課題理解"?"話を聞いて、聞き手が次にすることとして最も近いものを一つ選んでください。":type==="概要理解"?"話を聞いて、話の内容として最もよいものを一つ選んでください。":"音声を聞いて、重要なポイントと合っているものを一つ選んでください。";out.push(qObj({id:`ls-${type}-${c.id}`,type,score:"listening",instruction,question:"",choices:cs,answer:cs.indexOf(c.jp),explain:`音声の内容：${c.jp}`,audioText:c.jp,audioId:c.id.replace(/^g-/,"")}))}return out}
function buildListening(level,n){const qr=Math.min(4,Math.max(3,Math.round(n*.18))),needsVerbal=["N3","N4","N5"].includes(level),verbal=needsVerbal?Math.min(3,Math.max(2,Math.round(n*.12))):0;let out=[...buildQuickResponse(level,qr),...(verbal?buildQuickResponse(level,verbal,"発話表現"):[]),...buildListeningContent(level,n-qr-verbal)];if(out.length<n)out.push(...buildQuickResponse(level,n-out.length));return sample(unique(out),n)}
function buildSection(level,section,mode){const scale=mode==="quick"?.42:1,plan=Object.fromEntries(Object.entries(section.plan).map(([k,v])=>[k,Math.max(3,Math.round(v*scale))]));let qs=[];if(plan.vocab)qs.push(...buildVocab(level,plan.vocab));if(plan.grammar)qs.push(...buildGrammar(level,plan.grammar));if(plan.reading)qs.push(...buildReading(level,plan.reading));if(plan.listening)qs.push(...buildListening(level,plan.listening));return shuffle(qs)}
function buildTest(){const level=currentLevel(),mode=currentMode(),cfg=CFG[level];return{level,mode,sections:cfg.sections.map((s,i)=>({...s,minutes:mode==="quick"?Math.max(5,Math.round(s.min*.12)):s.min,questions:buildSection(level,s,mode)})),sectionIndex:0,qIndex:0,startAt:Date.now(),history:[]}}
function start(){if(!loadDone)return;state=buildTest();if(!state.sections.every(s=>s.questions.length)){alert("題庫暫時不足，請重新載入頁面後再試。");return}$("#setup").style.display="none";$("#resultPage").style.display="none";$("#sectionGate").style.display="none";$("#exam").style.display="block";startSection()}
function section(){return state.sections[state.sectionIndex]}
function question(){return section().questions[state.qIndex]}
function startSection(){clearTimer();state.qIndex=0;const s=section();state.timeLeft=s.minutes*60;$("#exam").style.display="block";$("#sectionGate").style.display="none";renderQuestion();tick();timerId=setInterval(()=>{state.timeLeft--;tick();if(state.timeLeft<=0){clearTimer();finishSection(true)}},1000)}
function tick(){const t=Math.max(0,state.timeLeft||0),m=String(Math.floor(t/60)).padStart(2,"0"),s=String(t%60).padStart(2,"0");$("#timer").textContent=`⏱ ${m}:${s}`;$("#timer").classList.toggle("danger",t<=300)}
function renderQuestion(){stopAudio();const s=section(),q=question();$("#sectionTitle").textContent=`${state.level} · ${s.title}`;$("#sectionProgress").textContent=`第 ${state.sectionIndex+1} / ${state.sections.length} 部分`;$("#questionProgress").textContent=`問題 ${state.qIndex+1} / ${s.questions.length}`;$("#qType").textContent=q.type;$("#instruction").textContent=q.instruction;$("#passage").style.display=q.passage?"block":"none";$("#passage").textContent=q.passage||"";$("#question").textContent=q.question||"";const listening=q.score==="listening";$("#listenBox").style.display=listening?"block":"none";$("#listenStatus").textContent=q.audioPlayed?"此題音聲已播放（正式模擬不重播）":"按下播放後只播放一次";$("#playAudio").disabled=q.audioPlayed;$("#choices").innerHTML=q.choices.map((c,i)=>`<button class="choice${q.user===i?" selected":""}" data-i="${i}"><strong>${i+1}.</strong> ${esc(c)}</button>`).join("");$$('.choice').forEach(b=>b.onclick=()=>selectAnswer(+b.dataset.i));$("#prev").disabled=state.qIndex===0;$("#next").textContent=state.qIndex===s.questions.length-1?"交卷本部分 →":"下一題 →";$("#flag").textContent=q.flag?"★ 已標記":"☆ 標記"}
function selectAnswer(i){question().user=i;renderQuestion()}
function next(){const s=section();if(state.qIndex>=s.questions.length-1){if(confirm("要提交本部分嗎？提交後不能返回修改答案。"))finishSection(false);return}state.qIndex++;renderQuestion()}
function prev(){if(state.qIndex>0){state.qIndex--;renderQuestion()}}
function flag(){question().flag=!question().flag;$("#flag").textContent=question().flag?"★ 已標記":"☆ 標記"}
function finishSection(timeout){clearTimer();stopAudio();const s=section(),blank=s.questions.filter(q=>q.user===null).length;$("#exam").style.display="none";$("#sectionGate").style.display="block";if(state.sectionIndex>=state.sections.length-1){$("#gateBig").textContent="試驗完成";$("#gateText").textContent=timeout?`時間到。本部分有 ${blank} 題未作答，未作答按錯題計算。`:`最後一部分已提交；${blank?`${blank} 題未作答，按錯題計算。`:"所有題目已提交。"}`;$("#nextSection").textContent="查看成績 →";$("#nextSection").onclick=finishTest}else{$("#gateBig").textContent=timeout?"時間到":"本部分完成";$("#gateText").textContent=`${s.title} 已提交。${blank?`有 ${blank} 題未作答，按錯題計算。`:""} 下一部分開始後會使用新的計時。`;$("#nextSection").textContent="開始下一部分 →";$("#nextSection").onclick=()=>{state.sectionIndex++;startSection()}}}
function stopAudio(){if(activeAudio){try{activeAudio.pause()}catch{}activeAudio=null}try{speechSynthesis.cancel()}catch{}}
function recUrls(rec){const a=Array.isArray(rec?.urls)?rec.urls:[rec?.url,rec?.backupUrl];return[...new Set(a.filter(Boolean))]}
async function playUrlList(urls,i=0){if(i>=urls.length)throw Error("no audio");return new Promise((resolve,reject)=>{const a=new Audio(urls[i]);activeAudio=a;a.onended=()=>{activeAudio=null;resolve()};a.onerror=async()=>{activeAudio=null;try{await playUrlList(urls,i+1);resolve()}catch(e){reject(e)}};a.play().catch(async()=>{activeAudio=null;try{await playUrlList(urls,i+1);resolve()}catch(e){reject(e)}})})}
function speakDevice(text){return new Promise((resolve,reject)=>{if(!("speechSynthesis" in window))return reject(Error("no speech"));const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.94;const vs=speechSynthesis.getVoices().filter(v=>/^ja/i.test(v.lang));u.voice=vs.find(v=>/^ja-JP$/i.test(v.lang))||vs[0]||null;u.onend=resolve;u.onerror=reject;speechSynthesis.cancel();speechSynthesis.speak(u)})}
async function playAudio(){const q=question();if(q.audioPlayed)return;q.audioPlayed=true;$("#playAudio").disabled=true;$("#listenStatus").textContent="播放中…";try{const rec=voicevoxIndex?.items?.[q.audioId],urls=recUrls(rec);if(urls.length)await playUrlList(urls);else await speakDevice(q.audioText);$("#listenStatus").textContent="播放完畢（本題不能重播）"}catch{$("#listenStatus").textContent="語音播放失敗；此題可再次嘗試";q.audioPlayed=false;$("#playAudio").disabled=false}}
function rawStats(){const all=state.sections.flatMap(s=>s.questions),groups={language:[],reading:[],listening:[]};all.forEach(q=>groups[q.score].push(q));const calc=a=>({right:a.filter(q=>q.user===q.answer).length,total:a.length,ratio:a.length?a.filter(q=>q.user===q.answer).length/a.length:0});return{all,language:calc(groups.language),reading:calc(groups.reading),listening:calc(groups.listening)}}
function scoreTest(){const r=rawStats(),level=state.level;let boxes=[],total=0,passSections=true;if(["N1","N2","N3"].includes(level)){for(const [key,label] of [["language","言語知識（文字・語彙・文法）"],["reading","読解"],["listening","聴解"]]){const v=Math.round(r[key].ratio*60);boxes.push({key,label,score:v,max:60,min:19,raw:r[key]});total+=v;if(v<19)passSections=false}}else{const lrRight=r.language.right+r.reading.right,lrTotal=r.language.total+r.reading.total,lrRatio=lrTotal?lrRight/lrTotal:0,lr=Math.round(lrRatio*120),ls=Math.round(r.listening.ratio*60);boxes=[{key:"lr",label:"言語知識（文字・語彙・文法）・読解",score:lr,max:120,min:38,raw:{right:lrRight,total:lrTotal,ratio:lrRatio}},{key:"listening",label:"聴解",score:ls,max:60,min:19,raw:r.listening}];total=lr+ls;if(lr<38||ls<19)passSections=false}return{...r,boxes,total,passed:total>=CFG[level].pass&&passSections}}
function finishTest(){stopAudio();const sc=scoreTest();$("#sectionGate").style.display="none";$("#resultPage").style.display="block";$("#resultLevel").textContent=`JLPT ${state.level} ${state.mode==="quick"?"快速模擬":"標準模擬"}`;$("#resultStatus").textContent=sc.passed?"合格圏":"未達合格圏";$("#resultStatus").className=`big ${sc.passed?"pass":"fail"}`;$("#resultTotal").textContent=`${sc.total} / 180`;$("#scoreGrid").innerHTML=sc.boxes.map(b=>`<div class="scorebox"><span>${esc(b.label)}</span><strong class="${b.score>=b.min?"pass":"fail"}">${b.score} / ${b.max}</strong><div class="muted">最低基準 ${b.min} · 原始正答 ${b.raw.right}/${b.raw.total}</div></div>`).join("");$("#resultNote").textContent=`${state.level} 總合格基準為 ${CFG[state.level].pass}/180，並且每個 scoring section 都必須達到最低分。本站按原始正答率換算成模擬分數；官方 JLPT 採 scaled score，所以兩者不會完全相同。`;renderReview(true);saveResult(sc);window.scrollTo({top:0,behavior:"smooth"})}
function saveResult(sc){try{const hist=JSON.parse(localStorage.getItem("jlpt_mock_history")||"[]");hist.unshift({at:new Date().toISOString(),level:state.level,mode:state.mode,total:sc.total,passed:sc.passed});localStorage.setItem("jlpt_mock_history",JSON.stringify(hist.slice(0,20)))}catch{}}
function renderReview(wrongOnly){const all=state.sections.flatMap((s,si)=>s.questions.map((q,qi)=>({...q,_section:s.title,_n:qi+1}))),rows=wrongOnly?all.filter(q=>q.user!==q.answer):all;$("#reviewList").innerHTML=rows.length?rows.map((q,i)=>{const ok=q.user===q.answer,chosen=q.user===null?"未作答":q.choices[q.user],correct=q.choices[q.answer];return`<details class="review-item ${ok?"":"bad"}"><summary>${ok?"✅":"❌"} ${esc(q.type)} · ${esc(q._section)} · 問題 ${q._n}</summary><div class="review-body">${q.passage?`<div class="passage">${esc(q.passage)}</div>`:""}${q.question?`<div class="jp">${esc(q.question)}</div>`:""}${q.audioText?`<div class="answerline"><strong>音聲內容：</strong>${esc(q.audioText)}</div>`:""}<div class="answerline"><strong>你的答案：</strong>${esc(chosen)}</div><div class="answerline pass"><strong>正確答案：</strong>${esc(correct)}</div><div class="answerline"><strong>說明：</strong>${esc(q.explain||"—")}</div></div></details>`}).join(""):"<div class='notice'>沒有錯題。🎉</div>"}
function restart(){clearTimer();stopAudio();state=null;$("#resultPage").style.display="none";$("#exam").style.display="none";$("#sectionGate").style.display="none";$("#setup").style.display="grid";renderAvailability();window.scrollTo({top:0,behavior:"smooth"})}
function clearTimer(){if(timerId){clearInterval(timerId);timerId=null}}
$$('input[name=level],input[name=mode]').forEach(x=>x.onchange=renderAvailability);$("#start").onclick=start;$("#next").onclick=next;$("#prev").onclick=prev;$("#flag").onclick=flag;$("#playAudio").onclick=playAudio;$("#reviewWrong").onclick=()=>renderReview(true);$("#reviewAll").onclick=()=>renderReview(false);$("#restart").onclick=restart;window.addEventListener("beforeunload",e=>{if(state&&$("#exam").style.display==="block"){e.preventDefault();e.returnValue=""}});renderAvailability();loadAll();
})();
