(function(){
'use strict';
var W=window.WA;if(!W)return;
if(document.getElementById('vocabBrowser'))return;
var setup=document.getElementById('setup');if(!setup)return;
var aside=setup.querySelector('aside.card');if(!aside)return;
var style=document.createElement('style');
style.textContent='.right-stack{display:flex;flex-direction:column;gap:14px;min-width:0}.vocab-browser{min-width:0}.vocab-browser-head{display:flex;flex-direction:column;gap:9px}.vocab-tools{display:grid;grid-template-columns:1fr 88px;gap:7px}.vocab-search{width:100%;min-width:0;padding:10px 11px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--text)}.vocab-page-size{width:100%;padding:10px 7px;border:1px solid var(--line);border-radius:10px;background:#fff}.kana-title{font-size:12px;font-weight:800;color:var(--muted);margin:12px 0 7px}.kana-subtitle{font-size:11px;font-weight:800;color:var(--muted);margin:9px 0 5px}.kana-index{display:flex;flex-direction:column;gap:5px;align-items:flex-start}.kana-row{display:flex;gap:5px;align-items:center;flex-wrap:nowrap;min-height:31px}.kana-btn{width:34px;height:31px;padding:0;border:1px solid var(--line);border-radius:8px;background:#fff;font-weight:800;font-size:13px;display:inline-flex;align-items:center;justify-content:center}.kana-btn.all{width:auto;padding:0 12px}.kana-btn.active{background:var(--blue2);border-color:var(--blue);color:var(--blue)}.vocab-list{margin-top:12px;border-top:1px solid var(--line);max-height:720px;overflow:auto}.vocab-row{display:grid;grid-template-columns:54px minmax(0,1fr) auto;grid-template-areas:"play jp meta" "play reading reading" "play meaning meaning";gap:5px 8px;align-items:start;padding:10px 2px;border-bottom:1px solid var(--line)}.vocab-play{grid-area:play;padding:8px 5px;align-self:center}.vocab-jp{grid-area:jp;font-size:18px;font-weight:850;font-family:"Yu Mincho","Hiragino Mincho ProN","Noto Serif JP",serif;min-width:0;overflow-wrap:anywhere}.vocab-reading{grid-area:reading;font-size:14px;font-weight:750;color:#465269}.vocab-meaning{grid-area:meaning;font-size:13px;line-height:1.45}.vocab-meta{grid-area:meta;font-size:11px;color:var(--muted);font-weight:800;white-space:nowrap}.vocab-pager{display:flex;justify-content:center;align-items:center;gap:7px;flex-wrap:wrap;margin-top:11px}.vocab-empty{text-align:center;color:var(--muted);padding:22px 8px}.vocab-audio-status{text-align:center;margin-top:9px;min-height:20px;line-height:1.45}@media(max-width:720px){.right-stack{gap:14px}.vocab-list{max-height:620px}.vocab-tools{grid-template-columns:1fr 90px}.kana-btn{width:32px}.kana-row{gap:4px}}';
document.head.appendChild(style);
var right=setup.querySelector('.right-stack');
if(!right){right=document.createElement('div');right.className='right-stack';setup.insertBefore(right,aside);right.appendChild(aside);}
var section=document.createElement('section');section.id='vocabBrowser';section.className='card vocab-browser';
var BASIC_ROWS=[['あ','い','う','え','お'],['か','き','く','け','こ'],['さ','し','す','せ','そ'],['た','ち','つ','て','と'],['な','に','ぬ','ね','の'],['は','ひ','ふ','へ','ほ'],['ま','み','む','め','も'],['や','ゆ','よ'],['ら','り','る','れ','ろ'],['わ','を','ん']];
var VOICED_ROWS=[['が','ぎ','ぐ','げ','ご'],['ざ','じ','ず','ぜ','ぞ'],['だ','ぢ','づ','で','ど'],['ば','び','ぶ','べ','ぼ'],['ぱ','ぴ','ぷ','ぺ','ぽ'],['ゔ']];
function kanaButton(k,extra){return '<button class="kana-btn'+(extra?' '+extra:'')+'" type="button" data-k="'+k+'">'+(k||'全部')+'</button>';}
function kanaRows(rows){return rows.map(function(row){return '<div class="kana-row">'+row.map(function(k){return kanaButton(k,'');}).join('')+'</div>';}).join('');}
section.innerHTML='<div class="vocab-browser-head"><div><h2>📋 單字清單｜逐字試聽</h2><div id="vocabListSummary" class="muted">單字載入後會顯示目前所選 JLPT 等級。</div></div><div class="vocab-tools"><input id="vocabSearch" class="vocab-search" type="search" placeholder="搜尋漢字、假名或繁體中文"><select id="vocabPageSize" class="vocab-page-size" aria-label="每頁數量"><option value="25" selected>25 / 頁</option><option value="50">50 / 頁</option><option value="100">100 / 頁</option></select></div></div><div class="kana-title">五十音索引｜按開頭平假名篩選</div><div id="kanaIndex" class="kana-index"><div class="kana-row">'+kanaButton('','all active')+'</div>'+kanaRows(BASIC_ROWS)+'<div class="kana-subtitle">濁音・半濁音</div>'+kanaRows(VOICED_ROWS)+'</div><div id="vocabList" class="vocab-list"><div class="vocab-empty">正在載入單字…</div></div><div class="vocab-pager"><button id="vocabPrev" class="btn">← 上一頁</button><span id="vocabPage" class="pill">1 / 1</span><button id="vocabNext" class="btn">下一頁 →</button></div><div id="vocabAudioStatus" class="muted vocab-audio-status">按 ▶ 聽，可用上方所選 Supertonic 聲線逐字試聽。</div>';
right.appendChild(section);
var page=1,view=[],busy=false,selectedKana='';
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c];});}
function hira(s){return String(s||'').replace(/[ァ-ヶ]/g,function(c){return String.fromCharCode(c.charCodeAt(0)-96);});}
function firstKana(w){var r=hira(w.reading||'').replace(/^[\s・ー]+/,'');return r.charAt(0)||'';}
function current(){var levels=W.levels?W.levels():[];var q=(document.getElementById('vocabSearch').value||'').trim().toLowerCase();var a=(W.words||[]).filter(function(w){if(levels.indexOf(w.level)<0)return false;if(selectedKana&&firstKana(w)!==selectedKana)return false;if(!q)return true;return [w.kanji,w.displayWord,w.reading,w.meaning,w.level].some(function(x){return String(x||'').toLowerCase().indexOf(q)>=0;});});a.sort(function(x,y){return hira(x.reading||'').localeCompare(hira(y.reading||''),'ja')||String(x.displayWord||x.kanji||'').localeCompare(String(y.displayWord||y.kanji||''),'ja');});return a;}
function render(){view=current();var size=Number(document.getElementById('vocabPageSize').value)||25;var pages=Math.max(1,Math.ceil(view.length/size));page=Math.max(1,Math.min(page,pages));var start=(page-1)*size,items=view.slice(start,start+size);var levels=W.levels?W.levels():[];var kanaText=selectedKana?'｜「'+selectedKana+'」開頭':'';document.getElementById('vocabListSummary').textContent=(levels.length?levels.join(' + '):'未選擇等級')+kanaText+'｜找到 '+view.length.toLocaleString()+' 個單字';document.getElementById('vocabPage').textContent=page+' / '+pages;document.getElementById('vocabPrev').disabled=page<=1;document.getElementById('vocabNext').disabled=page>=pages;var list=document.getElementById('vocabList');if(!items.length){list.innerHTML='<div class="vocab-empty">沒有符合目前等級／假名／搜尋條件的單字。</div>';return;}list.innerHTML=items.map(function(w,i){var written=w.kanji||w.displayWord||w.reading;return '<div class="vocab-row"><button class="btn vocab-play" data-i="'+(start+i)+'" title="試聽 '+esc(w.reading)+'">▶ 聽</button><div class="vocab-jp">'+esc(written)+'</div><div class="vocab-reading">'+esc(w.reading)+'</div><div class="vocab-meaning">'+esc(w.meaning)+'</div><div class="vocab-meta">'+esc(w.level+(w.estimated?' 推定':''))+'</div></div>';}).join('');list.querySelectorAll('.vocab-play').forEach(function(b){b.onclick=async function(){if(busy)return;var w=view[Number(b.dataset.i)];if(!w||!W.speak)return;var status=document.getElementById('vocabAudioStatus'),buttons=[].slice.call(list.querySelectorAll('.vocab-play'));busy=true;buttons.forEach(function(x){x.disabled=true;});status.textContent='🔊 正在播放：'+(w.kanji||w.displayWord||w.reading)+'（'+w.reading+'）';try{var used=await W.speak(w.reading);status.textContent=used?'✅ 已播放：'+(w.kanji||w.displayWord||w.reading)+'｜Supertonic '+used:'⚠️ 語音尚未準備完成，請再試一次。';}catch(e){status.textContent='⚠️ 播放失敗：'+(e&&e.message?e.message:String(e));}finally{busy=false;buttons.forEach(function(x){x.disabled=false;});}};});}
var oldAvailable=W.available;W.available=function(){if(oldAvailable)oldAvailable.apply(W,arguments);page=1;render();};
document.getElementById('vocabSearch').oninput=function(){page=1;render();};
document.getElementById('vocabPageSize').onchange=function(){page=1;render();};
document.querySelectorAll('#kanaIndex .kana-btn').forEach(function(b){b.onclick=function(){selectedKana=b.dataset.k||'';document.querySelectorAll('#kanaIndex .kana-btn').forEach(function(x){x.classList.toggle('active',x===b);});page=1;render();};});
document.getElementById('vocabPrev').onclick=function(){if(page>1&&!busy){page--;render();section.scrollIntoView({behavior:'smooth',block:'start'});}};
document.getElementById('vocabNext').onclick=function(){var size=Number(document.getElementById('vocabPageSize').value)||25;if(!busy&&page<Math.max(1,Math.ceil(view.length/size))){page++;render();section.scrollIntoView({behavior:'smooth',block:'start'});}};
render();
})();