(function(){'use strict';var W=window.WA;if(!W)return;var page=1,selectedKana='',view=[],audioBusy=false;var VOICES={F1:['🌙 沉穩低柔女聲（F1）','F1：沉穩、略低音、平靜而穩定。適合較成熟、低柔的女聲。'],F2:['🌸 明亮活潑女聲（F2）','F2：明亮、愉快、活潑而年輕。適合可愛、角色感較強的女聲。'],F3:['🎙️ 專業播音女聲（F3）','F3：清晰、專業、播音員風格。適合正式或新聞式發音。'],F4:['✨ 清晰自信女聲（F4）','F4：清脆、自信、表達力強。適合有力而清楚的女聲。'],F5:['💕 溫柔療癒女聲（F5）','F5：親切、溫柔、輕聲而舒緩。適合柔和、陪伴感較強的女聲。'],M1:['⚡ 活力自信男聲（M1）','M1：活潑、正面、自信而清晰。適合一般及有活力的男聲。'],M2:['🌑 低沉穩重男聲（M2）','M2：低沉、厚實、冷靜而嚴肅。適合成熟、穩重的男聲。'],M3:['🧭 權威專業男聲（M3）','M3：精緻、權威、自信可信。適合專業演說或正式旁白。'],M4:['🙂 柔和親切男聲（M4）','M4：柔和、中性、年輕而親切。適合教育及輕鬆內容。'],M5:['📖 溫暖舒緩男聲（M5）','M5：溫暖、輕聲、平靜而舒緩。適合故事及放鬆內容。'],random:['🎲 每個單字隨機聲線','每次試聽隨機使用 F1–F5／M1–M5，避免習慣單一聲線。']};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function hira(s){return String(s||'').replace(/[ァ-ヶ]/g,function(c){return String.fromCharCode(c.charCodeAt(0)-96);}).replace(/[ぁぃぅぇぉゃゅょっ]/g,function(c){return{'ぁ':'あ','ぃ':'い','ぅ':'う','ぇ':'え','ぉ':'お','ゃ':'や','ゅ':'ゆ','ょ':'よ','っ':'つ'}[c]||c;});}
function firstKana(w){var r=hira(w.reading||'').replace(/^[\s・ー]+/,'');return r.charAt(0)||'';}
function engine(){var e=document.getElementById('audioEngine');return e?e.value:'supertonic3';}
W.levels=function(){return ['N1','N2','N3','N4','N5'].filter(function(l){var x=document.getElementById(l.toLowerCase());return x&&x.checked;});};
function filtered(){var levels=W.levels(),q=(document.getElementById('search').value||'').trim().toLowerCase();var a=(W.words||[]).filter(function(w){if(levels.indexOf(w.level)<0)return false;if(selectedKana&&firstKana(w)!==selectedKana)return false;if(!q)return true;return [w.kanji,w.displayWord,w.reading,w.meaning,w.level].some(function(x){return String(x||'').toLowerCase().indexOf(q)>=0;});});a.sort(function(a,b){return hira(a.reading||'').localeCompare(hira(b.reading||''),'ja')||String(a.displayWord||a.kanji||'').localeCompare(String(b.displayWord||b.kanji||''),'ja');});return a;}
function setBusy(v){audioBusy=v;document.querySelectorAll('.play-btn').forEach(function(b){b.disabled=v;});var s=document.getElementById('sampleVoice');if(s)s.disabled=v;var voice=document.getElementById('voice');if(voice)voice.disabled=v;var eng=document.getElementById('audioEngine');if(eng)eng.disabled=v;}
function engineLabel(e){return e==='voicevox'?'VOICEVOX':e==='aivis'?'AivisSpeech / Style-Bert-VITS':e==='device'?'裝置 Japanese voice':'Supertonic 3';}
async function speakWord(w){if(audioBusy)return;setBusy(true);var status=document.getElementById('audioStatus'),name=w.kanji||w.displayWord||w.reading;status.textContent='🔊 正在播放：'+name+'（'+w.reading+'）';try{if(!W.speak){status.textContent='⚠️ 多聲線模組尚未載入。';return;}var used=await W.speak(w.reading,w);status.textContent=used?'✅ 已播放：'+name+'｜'+engineLabel(engine()):'⚠️ 語音暫時無法播放。';}catch(e){status.textContent='⚠️ 播放失敗：'+(e&&e.message?e.message:String(e));}finally{setBusy(false);}}
function render(){view=filtered();var size=Number(document.getElementById('pageSize').value)||50,pages=Math.max(1,Math.ceil(view.length/size));page=Math.max(1,Math.min(page,pages));var start=(page-1)*size,items=view.slice(start,start+size),levels=W.levels();var filterText=selectedKana?'｜「'+selectedKana+'」開頭':'';document.getElementById('summary').textContent=(levels.length?levels.join(' + '):'未選擇等級')+filterText+'｜找到 '+view.length.toLocaleString()+' 個單字';document.getElementById('pageInfo').textContent=page+' / '+pages;document.getElementById('prevPage').disabled=page<=1;document.getElementById('nextPage').disabled=page>=pages;var body=document.getElementById('vocabBody');if(!items.length){body.innerHTML='<tr><td colspan="5" class="empty">沒有符合目前等級／五十音／搜尋條件的單字。</td></tr>';return;}body.innerHTML=items.map(function(w,i){var written=w.kanji||w.displayWord||w.reading;return '<tr><td class="play-cell"><button class="btn play-btn" data-i="'+(start+i)+'">▶ 聽</button></td><td class="word-cell">'+esc(written)+'</td><td class="reading-cell">'+esc(w.reading)+'</td><td class="meaning-cell">'+esc(w.meaning)+'</td><td class="level-cell">'+esc(w.level+(w.estimated?' 推定':''))+'</td></tr>';}).join('');body.querySelectorAll('.play-btn').forEach(function(b){b.onclick=function(){var w=view[Number(b.dataset.i)];if(w)speakWord(w);};});}
W.available=function(){page=1;render();};
var voice=document.getElementById('voice');voice.innerHTML=Object.keys(VOICES).map(function(k){return '<option value="'+k+'"'+(k==='F3'?' selected':'')+'>'+VOICES[k][0]+'</option>';}).join('');function voiceDesc(){document.getElementById('voiceDesc').textContent=(VOICES[voice.value]||VOICES.F3)[1];}voice.onchange=voiceDesc;voiceDesc();
document.getElementById('sampleVoice').onclick=async function(){if(audioBusy)return;setBusy(true);var st=document.getElementById('voiceStatus');try{var sample=(W.words||[]).find(function(w){return w.reading==='ありがとう';})||(W.words||[])[0];if(!sample)throw new Error('單字資料尚未載入');st.textContent='正在準備 '+engineLabel(engine())+' 試聽…';var used=await W.speak(sample.reading,sample);st.textContent=used?'✅ 試聽完成：'+engineLabel(engine())+'｜'+sample.reading:'⚠️ 試聽暫時無法播放。';}catch(e){st.textContent='⚠️ 試聽失敗：'+(e&&e.message?e.message:String(e));}finally{setBusy(false);}};
document.querySelectorAll('.level input').forEach(function(x){x.onchange=W.available;});document.querySelectorAll('.preset').forEach(function(b){b.onclick=function(){var a=b.dataset.l.split(',');document.querySelectorAll('.level input').forEach(function(x){x.checked=a.indexOf(x.value)>=0;});W.available();};});document.querySelectorAll('.kana-btn').forEach(function(b){b.onclick=function(){selectedKana=b.dataset.k||'';document.querySelectorAll('.kana-btn').forEach(function(x){x.classList.toggle('active',x===b);});page=1;render();};});document.getElementById('search').oninput=function(){page=1;render();};document.getElementById('pageSize').onchange=function(){page=1;render();};document.getElementById('prevPage').onclick=function(){if(page>1&&!audioBusy){page--;render();document.querySelector('.table-wrap').scrollIntoView({behavior:'smooth',block:'start'});}};document.getElementById('nextPage').onclick=function(){var size=Number(document.getElementById('pageSize').value)||50,pages=Math.max(1,Math.ceil(view.length/size));if(page<pages&&!audioBusy){page++;render();document.querySelector('.table-wrap').scrollIntoView({behavior:'smooth',block:'start'});}};render();W.loadData();})();