#!/usr/bin/env python3
from pathlib import Path
p=Path('listening.html');s=p.read_text(encoding='utf-8')
assert '日本語聽解挑戰 v1.8｜JLPT N1–N5' in s
s=s.replace('日本語聽解挑戰 v1.8｜JLPT N1–N5','日本語聽解挑戰 v1.9｜JLPT N1–N5',1)
old='''function selectedVoicevoxSpeaker(){return $("#voicevoxVoice")?.value||"random"}
function pool(){let p=items.filter(x=>selectedLevels().includes(x.level)&&mutations(x.jp).length>=3);if($("input[name=audioEngine]:checked")?.value==="voicevox"){const speaker=selectedVoicevoxSpeaker();if(speaker!=="random")p=p.filter(x=>voicevoxIndex?.items?.[x.id]?.speaker===speaker)}if($("input[name=mode]:checked").value==="wrong")p=p.filter(x=>wrong.has(x.id));return uniqueBySentence(p)}'''
new='''function selectedVoicevoxSpeaker(){return $("#voicevoxVoice")?.value||"random"}
function pool(){let p=items.filter(x=>selectedLevels().includes(x.level)&&mutations(x.jp).length>=3);if($("input[name=audioEngine]:checked")?.value==="voicevox"&&!voicevoxFullIndex){const speaker=selectedVoicevoxSpeaker();if(speaker!=="random")p=p.filter(x=>voicevoxIndex?.items?.[x.id]?.speaker===speaker)}if($("input[name=mode]:checked").value==="wrong")p=p.filter(x=>wrong.has(x.id));return uniqueBySentence(p)}'''
assert old in s;s=s.replace(old,new,1)
start=s.index('let voicevoxIndex={version:2,items:{}};');end=s.index('\n\nasync function waitForAiModule()',start)
replacement=r'''let voicevoxIndex={version:2,items:{}};
let voicevoxFullIndex=null;
let activeVoicevoxStopTimer=null;
function voicevoxUrls(rec){const raw=Array.isArray(rec?.urls)?rec.urls:[rec?.url,rec?.backupUrl];return[...new Set(raw.filter(x=>typeof x==="string"&&x.trim()).map(x=>x.trim()))]}
function voicevoxProvider(url){return /huggingface\.co\//i.test(url)?"Hugging Face 備援":"GitHub Releases"}
function populateVoicevoxVoices(){const sel=$("#voicevoxVoice"),desc=$("#voicevoxVoiceDesc");if(!sel)return;const wanted=load("jplistening_voicevox_speaker","random");if(voicevoxFullIndex){const rows=Object.entries(voicevoxFullIndex.speakers||{}).sort((a,b)=>String(a[1]?.speaker||"").localeCompare(String(b[1]?.speaker||""),"ja"));sel.innerHTML='<option value="random">🎲 每題隨機 VOICEVOX 聲線（每個聲線都有完整題庫）</option>'+rows.map(([key,v])=>`<option value="${esc(key)}">${esc(v.speaker)}（${Number(v.questionCount||0).toLocaleString()} 題）</option>`).join("");let value=rows.some(([key])=>key===wanted)?wanted:"random";if(value==="random"){const byName=rows.find(([,v])=>v.speaker===wanted);if(byName)value=byName[0]}sel.value=value;updateVoicevoxVoice();return}const counts=new Map();Object.values(voicevoxIndex?.items||{}).forEach(r=>{const n=String(r?.speaker||"").trim();if(n)counts.set(n,(counts.get(n)||0)+1)});const rows=[...counts.entries()].sort((a,b)=>a[0].localeCompare(b[0],"ja"));sel.innerHTML='<option value="random">🎲 每題使用不同預錄聲線（舊版完整題庫）</option>'+rows.map(([name,n])=>`<option value="${esc(name)}">${esc(name)}（${n.toLocaleString()} 題）</option>`).join("");sel.value=rows.some(([name])=>name===wanted)?wanted:"random";updateVoicevoxVoice()}
function updateVoicevoxVoice(){const value=$("#voicevoxVoice")?.value||"random",desc=$("#voicevoxVoiceDesc");save("jplistening_voicevox_speaker",value);if(!desc)return;if(voicevoxFullIndex){if(value==="random")desc.textContent=`✅ 完整聲線庫：${voicevoxFullIndex.speakerCount.toLocaleString()} 個 VOICEVOX 聲線，每個都有同一套 ${voicevoxFullIndex.indexed.toLocaleString()} 題。`;else{const v=voicevoxFullIndex.speakers?.[value];desc.textContent=v?`✅ ${v.speaker}／${v.style}：完整 ${Number(v.questionCount).toLocaleString()} 題；整次練習可以固定使用這個聲線。`:"聲線資料暫時無法讀取。"}availability();return}desc.textContent=value==="random"?`舊版 VOICEVOX 題庫：${Object.keys(voicevoxIndex?.items||{}).length.toLocaleString()} 題；43 聲線完整庫尚未切換。`:`舊版 ${value} 只包含部分題目；43 聲線完整庫尚未切換。`;availability()}
async function fetchJsonNoCache(url){const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function loadVoicevoxIndex(){const st=$("#voicevoxStatus");try{const d=await fetchJsonNoCache("./voicevox-full-index.json");if(d?.version!==4||d?.coverage!=="full-per-speaker"||Number(d?.speakerCount)!==43||Number(d?.indexed)!==3310||Number(d?.recordingCount)!==142330)throw new Error("完整聲線索引尚未完成");voicevoxFullIndex=d;voicevoxIndex={version:2,items:{}};populateVoicevoxVoices();st.textContent=`✅ VOICEVOX 完整聲線庫已準備：43 個聲線 × 3,310 題 = ${Number(d.recordingCount).toLocaleString()} 段錄音。GitHub Releases 主來源 + Hugging Face 自動備援。`;return d.indexed}catch(e){voicevoxFullIndex=null;try{const d=await fetchJsonNoCache("./voicevox-release-index.json");if(!d?.items)throw new Error("舊索引格式錯誤");voicevoxIndex=d;populateVoicevoxVoices();st.textContent=`⚠️ 43 聲線完整庫正在建置／驗證；目前安全保留舊版 ${Object.keys(d.items).length.toLocaleString()} 題輪替錄音。`;return Object.keys(d.items).length}catch{voicevoxIndex={version:2,items:{}};populateVoicevoxVoices();st.textContent="⚠️ VOICEVOX 音訊暫時無法讀取；將使用其他語音備援。";return 0}}}
function chosenFullSpeakerKey(){const chosen=selectedVoicevoxSpeaker();if(chosen!=="random"&&voicevoxFullIndex?.speakers?.[chosen])return chosen;if(game?.voicevoxSpeakerForQuestion)return game.voicevoxSpeakerForQuestion;const keys=Object.keys(voicevoxFullIndex?.speakers||{});if(!keys.length)return null;const key=keys[Math.floor(Math.random()*keys.length)];if(game)game.voicevoxSpeakerForQuestion=key;return key}
function fullPreparedFor(qid,speakerKey=null){if(!voicevoxFullIndex)return null;const key=speakerKey||chosenFullSpeakerKey(),sp=voicevoxFullIndex.speakers?.[key],level=String(qid||"").split("-")[0],sprite=sp?.sprites?.[level],seg=sprite?.segments?.[qid];if(!sp||!sprite||!Array.isArray(seg)||seg.length<2)return null;const start=Number(seg[0]),end=Number(seg[1]);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return null;return{candidates:[{url:sprite.githubUrl,provider:"GitHub Releases",audio:null},{url:sprite.hfUrl,provider:"Hugging Face 備援",audio:null}],segment:{start,end},out:{speaker:sp.speaker,style:sp.style,styleId:sp.styleId,credit:sp.credit,source:"VOICEVOX",speakerKey:key,text:voicevoxFullIndex.questions?.[qid]?.text||""}}}
async function prepareVoicevoxAudio(q){if(voicevoxFullIndex){const p=fullPreparedFor(q.id);if(p)return p}const rec=voicevoxIndex?.items?.[q.id],urls=voicevoxUrls(rec);if(!urls.length)return null;return{candidates:urls.map(url=>({url,provider:voicevoxProvider(url),audio:null})),segment:null,out:{...rec,source:"VOICEVOX"}}}
function waitMediaReady(a){if(a.readyState>=1)return Promise.resolve();return new Promise((resolve,reject)=>{let done=false;const clean=()=>{a.removeEventListener("loadedmetadata",ok);a.removeEventListener("error",bad)};const ok=()=>{if(done)return;done=true;clean();resolve()};const bad=()=>{if(done)return;done=true;clean();reject(new Error("媒體載入失敗"))};a.addEventListener("loadedmetadata",ok,{once:true});a.addEventListener("error",bad,{once:true});setTimeout(()=>{if(!done){done=true;clean();reject(new Error("媒體載入逾時"))}},15000)})}
async function candidateAudio(c){if(!c.audio||!c.audio.src){c.audio=new Audio(c.url);c.audio.preload="metadata"}await waitMediaReady(c.audio);return c.audio}
function clearVoicevoxStop(){if(activeVoicevoxStopTimer){clearTimeout(activeVoicevoxStopTimer);activeVoicevoxStopTimer=null}}
async function playAudioSegment(a,segment,rate){clearVoicevoxStop();a.pause();if(segment){a.currentTime=Math.max(0,segment.start);a.playbackRate=rate;await a.play();const ms=Math.max(80,((segment.end-segment.start)/rate)*1000+80);activeVoicevoxStopTimer=setTimeout(()=>{try{a.pause();a.currentTime=segment.start}catch{}activeVoicevoxStopTimer=null},ms);return}a.currentTime=0;a.playbackRate=rate;await a.play()}
async function playPreparedVoicevox(prepared,rate=1,forSample=false){let last=null;for(const c of prepared?.candidates||[]){try{const a=await candidateAudio(c);activeAiAudio=a;await playAudioSegment(a,prepared.segment,rate);const meta=prepared.out||{},who=[meta.speaker,meta.style].filter(Boolean).join("／");if(forSample){$("#sampleVoiceStatus").textContent=`✅ 試聽：${who||"VOICEVOX"} · ${c.provider} · ${meta.text||""}`;return true}$("#voicevoxStatus").textContent=c.provider==="Hugging Face 備援"?"✅ GitHub 音訊不可用，已自動切換 Hugging Face 備援。":`✅ VOICEVOX 正在使用 ${c.provider}。`;unlockAfterPlay(`VOICEVOX${who?" · "+who:""} · ${c.provider}`);return true}catch(e){last=e;c.audio=null;activeAiAudio=null}}throw last||new Error("所有 VOICEVOX 音訊來源均無法播放")}
async function playVoicevoxRecord(rec,rate=1,forSample=false){return playPreparedVoicevox({candidates:voicevoxUrls(rec).map(url=>({url,provider:voicevoxProvider(url),audio:null})),segment:null,out:{...rec,source:"VOICEVOX"}},rate,forSample)}
async function prepareVoicevoxSetupSample(){if(voicevoxFullIndex){const keys=Object.keys(voicevoxFullIndex.speakers||{});let key=selectedVoicevoxSpeaker();if(key==="random"||!voicevoxFullIndex.speakers?.[key])key=keys[0];const qid=Object.keys(voicevoxFullIndex.questions||{})[0];return fullPreparedFor(qid,key)}const name=selectedVoicevoxSpeaker(),rec=Object.values(voicevoxIndex?.items||{}).find(r=>name==="random"||r?.speaker===name);if(!rec)return null;return{candidates:voicevoxUrls(rec).map(url=>({url,provider:voicevoxProvider(url),audio:null})),segment:null,out:{...rec,source:"VOICEVOX"}}}
async function speakVoicevox(rate=1){try{let p=game.voicevoxPrepared;if(!p&&game.voicevoxPromise)p=await game.voicevoxPromise;if(!p)p=await prepareVoicevoxAudio(game.current);if(!p)throw new Error("此題沒有 VOICEVOX 音訊");game.voicevoxPrepared=p;return await playPreparedVoicevox(p,rate,false)}catch(e){$("#voicevoxStatus").textContent="⚠️ GitHub 與 Hugging Face 的 VOICEVOX 音訊暫時都無法播放；已改用其他語音備援。";return false}}'''
s=s[:start]+replacement+s[end:]
old='''if(mode==="voicevox"){const name=selectedVoicevoxSpeaker();const rec=Object.values(voicevoxIndex?.items||{}).find(r=>name==="random"||r?.speaker===name);if(!rec)throw new Error("目前找不到這個 VOICEVOX 聲線的試聽音訊");await playVoicevoxRecord(rec,1,true);return}'''
new='''if(mode==="voicevox"){const prepared=await prepareVoicevoxSetupSample();if(!prepared)throw new Error("目前找不到這個 VOICEVOX 聲線的試聽音訊");await playPreparedVoicevox(prepared,1,true);return}'''
assert old in s;s=s.replace(old,new,1)
old='''game.plays=0;game.lastAudioLabel="";game.voicevoxPrepared=null;game.voicevoxPromise=$("input[name=audioEngine]:checked")?.value==="voicevox"?prepareVoicevoxAudio(q):null;game.aiVoiceForQuestion=null;'''
new='''game.plays=0;game.lastAudioLabel="";clearVoicevoxStop();game.voicevoxPrepared=null;game.voicevoxSpeakerForQuestion=null;game.voicevoxPromise=$("input[name=audioEngine]:checked")?.value==="voicevox"?prepareVoicevoxAudio(q):null;game.aiVoiceForQuestion=null;'''
assert old in s;s=s.replace(old,new,1)
old='每個句子目前有一條已預錄 VOICEVOX 音訊。指定聲線時，遊戲會只使用已有該聲線的題目；選「每題使用不同預錄聲線」可使用完整題庫。GitHub Releases 播放失敗時會自動切換 Hugging Face。'
new='完整聲線庫完成後，每個可選 VOICEVOX 聲線都有相同 3,310 題。可整次練習固定一個聲線，或每題隨機；GitHub Releases 為主來源，Hugging Face 自動備援。完整庫驗證完成前會保留現有音訊。'
assert old in s;s=s.replace(old,new,1)
# stopAllAudio also cancels sprite stop timer when available.
s=s.replace('function stopAllAudio(){try{speechSynthesis.cancel()}catch{}if(activeAiAudio){try{activeAiAudio.pause();activeAiAudio.currentTime=0}catch{}activeAiAudio=null}}','function stopAllAudio(){try{speechSynthesis.cancel()}catch{}try{clearVoicevoxStop()}catch{}if(activeAiAudio){try{activeAiAudio.pause();activeAiAudio.currentTime=0}catch{}activeAiAudio=null}}',1)
p.write_text(s,encoding='utf-8');print('Patched Listening v1.9 for 43x3310 VOICEVOX audio sprites')
