#!/usr/bin/env python3
from pathlib import Path

p=Path('listening.html')
s=p.read_text(encoding='utf-8')
assert '日本語聽解挑戰 v1.8｜JLPT N1–N5' in s
s=s.replace('日本語聽解挑戰 v1.8｜JLPT N1–N5','日本語聽解挑戰 v1.9｜JLPT N1–N5',1)

old='''function selectedVoicevoxSpeaker(){return $("#voicevoxVoice")?.value||"random"}
function pool(){let p=items.filter(x=>selectedLevels().includes(x.level)&&mutations(x.jp).length>=3);if($("input[name=audioEngine]:checked")?.value==="voicevox"){const speaker=selectedVoicevoxSpeaker();if(speaker!=="random")p=p.filter(x=>voicevoxIndex?.items?.[x.id]?.speaker===speaker)}if($("input[name=mode]:checked").value==="wrong")p=p.filter(x=>wrong.has(x.id));return uniqueBySentence(p)}'''
new='''function selectedVoicevoxSpeaker(){return $("#voicevoxVoice")?.value||"random"}
function pool(){let p=items.filter(x=>selectedLevels().includes(x.level)&&mutations(x.jp).length>=3);if($("input[name=audioEngine]:checked")?.value==="voicevox"&&!voicevoxFullIndex){const speaker=selectedVoicevoxSpeaker();if(speaker!=="random")p=p.filter(x=>voicevoxIndex?.items?.[x.id]?.speaker===speaker)}if($("input[name=mode]:checked").value==="wrong")p=p.filter(x=>wrong.has(x.id));return uniqueBySentence(p)}'''
assert old in s
s=s.replace(old,new,1)

start=s.index('let voicevoxIndex={version:2,items:{}};')
end=s.index('\n\nasync function waitForAiModule()',start)
replacement=r'''let voicevoxIndex={version:2,items:{}};
let voicevoxFullIndex=null;
function voicevoxUrls(rec){const raw=Array.isArray(rec?.urls)?rec.urls:[rec?.url,rec?.backupUrl];return[...new Set(raw.filter(x=>typeof x==="string"&&x.trim()).map(x=>x.trim()))]}
function voicevoxProvider(url){return /huggingface\.co\//i.test(url)?"Hugging Face 備援":"GitHub Releases"}
function fullSpeakerRows(){return Object.entries(voicevoxFullIndex?.speakers||{}).sort((a,b)=>String(a[1]?.speaker||"").localeCompare(String(b[1]?.speaker||""),"ja"))}
function populateVoicevoxVoices(){const sel=$("#voicevoxVoice"),desc=$("#voicevoxVoiceDesc");if(!sel)return;const wanted=load("jplistening_voicevox_speaker","random");if(voicevoxFullIndex){const rows=fullSpeakerRows();sel.innerHTML='<option value="random">🎲 每題隨機 VOICEVOX 聲線（每個聲線都有完整題庫）</option>'+rows.map(([key,v])=>`<option value="${esc(key)}">${esc(v.speaker)}（${Number(v.questionCount||voicevoxFullIndex.indexed||0).toLocaleString()} 題）</option>`).join("");let resolved=rows.some(([key])=>key===wanted)?wanted:"random";if(resolved==="random"){const byName=rows.find(([,v])=>v.speaker===wanted);if(byName)resolved=byName[0]}sel.value=resolved;updateVoicevoxVoice();return}const counts=new Map();Object.values(voicevoxIndex?.items||{}).forEach(r=>{const n=String(r?.speaker||"").trim();if(n)counts.set(n,(counts.get(n)||0)+1)});const rows=[...counts.entries()].sort((a,b)=>a[0].localeCompare(b[0],"ja"));sel.innerHTML='<option value="random">🎲 每題使用不同預錄聲線（舊版完整題庫）</option>'+rows.map(([name,n])=>`<option value="${esc(name)}">${esc(name)}（${n.toLocaleString()} 題）</option>`).join("");sel.value=rows.some(([name])=>name===wanted)?wanted:"random";updateVoicevoxVoice()}
function updateVoicevoxVoice(){const sel=$("#voicevoxVoice"),desc=$("#voicevoxVoiceDesc");if(!sel||!desc)return;const value=sel.value||"random";save("jplistening_voicevox_speaker",value);if(voicevoxFullIndex){if(value==="random"){desc.textContent=`✅ 完整聲線庫：${voicevoxFullIndex.speakerCount.toLocaleString()} 個 VOICEVOX 聲線，每個都有同一套 ${voicevoxFullIndex.indexed.toLocaleString()} 題；每題隨機選一個聲線。`}else{const v=voicevoxFullIndex.speakers?.[value];desc.textContent=v?`✅ ${v.speaker}／${v.style}：完整 ${Number(v.questionCount||0).toLocaleString()} 題。整次練習可固定使用這個聲線。`:"VOICEVOX 聲線資料暫時無法讀取。"}availability();return}if(value==="random"){desc.textContent=`舊版 VOICEVOX 題庫：${Object.keys(voicevoxIndex?.items||{}).length.toLocaleString()} 題；完整聲線庫仍在建置／驗證中。`}else{const rows=Object.values(voicevoxIndex?.items||{}).filter(r=>r?.speaker===value);const styles=[...new Set(rows.map(r=>r?.style).filter(Boolean))];desc.textContent=`舊版 ${value}：目前 ${rows.length.toLocaleString()} 題${styles.length?`；${styles.slice(0,4).join("、")}${styles.length>4?"…":""}`:""}。完整 3,310 題／聲線庫尚未切換。`}availability()}
async function fetchJsonNoCache(url){const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function loadVoicevoxIndex(){const st=$("#voicevoxStatus");try{const d=await fetchJsonNoCache("./voicevox-full-index.json");if(d?.version!==3||d?.coverage!=="full-per-speaker"||Number(d?.speakerCount)!==43||Number(d?.indexed)!==3310||Number(d?.recordingCount)!==142330)throw new Error("完整聲線索引尚未完成");voicevoxFullIndex=d;voicevoxIndex={version:2,items:{}};populateVoicevoxVoices();st.textContent=`✅ VOICEVOX 完整聲線庫已準備：43 個聲線 × 3,310 題 = ${Number(d.recordingCount).toLocaleString()} 段錄音。GitHub Releases 主來源 + Hugging Face 自動備援。`;return d.indexed}catch(fullError){voicevoxFullIndex=null;try{const d=await fetchJsonNoCache("./voicevox-release-index.json");if(!d||typeof d!=="object"||!d.items)throw new Error("舊索引格式不正確");voicevoxIndex=d;const n=Object.keys(d.items||{}).length;const backed=Object.values(d.items||{}).filter(rec=>voicevoxUrls(rec).some(u=>/huggingface\.co\//i.test(u))).length;populateVoicevoxVoices();st.textContent=n?`⚠️ 完整 43 聲線庫正在建置／驗證；目前先使用舊版 ${n.toLocaleString()} 題輪替錄音${backed?`，${backed.toLocaleString()} 題有 Hugging Face 備援`:""}。`:"⚠️ VOICEVOX 完整聲線庫尚未完成；將使用其他語音備援。";return n}catch(e){voicevoxIndex={version:2,items:{}};populateVoicevoxVoices();st.textContent="⚠️ VOICEVOX 公開音訊暫時無法讀取；將使用其他語音備援。";return 0}}}
function chosenFullSpeakerKey(){const selected=selectedVoicevoxSpeaker();if(selected!=="random"&&voicevoxFullIndex?.speakers?.[selected])return selected;if(game?.voicevoxSpeakerForQuestion&&voicevoxFullIndex?.speakers?.[game.voicevoxSpeakerForQuestion])return game.voicevoxSpeakerForQuestion;const keys=Object.keys(voicevoxFullIndex?.speakers||{});if(!keys.length)return null;const key=keys[Math.floor(Math.random()*keys.length)];if(game)game.voicevoxSpeakerForQuestion=key;return key}
function fullPreparedFor(qid,speakerKey=null){if(!voicevoxFullIndex)return null;const key=speakerKey||chosenFullSpeakerKey();const sp=voicevoxFullIndex.speakers?.[key];const level=String(qid||"").split("-")[0];const bundle=sp?.bundles?.[level],member=bundle?.members?.[qid];if(!sp||!bundle||!Array.isArray(member)||member.length<2)return null;const offset=Number(member[0]),size=Number(member[1]);if(!Number.isFinite(offset)||!Number.isFinite(size)||size<500)return null;return{candidates:[{url:bundle.githubUrl,provider:"GitHub Releases",offset,size,audio:null,objectUrl:null},{url:bundle.hfUrl,provider:"Hugging Face 備援",offset,size,audio:null,objectUrl:null}],out:{speaker:sp.speaker,style:sp.style,styleId:sp.styleId,credit:sp.credit,source:"VOICEVOX",speakerKey:key,text:voicevoxFullIndex.questions?.[qid]?.text||""}}}
async function prepareVoicevoxAudio(q){if(voicevoxFullIndex){const prepared=fullPreparedFor(q.id);if(prepared)return prepared}const rec=voicevoxIndex?.items?.[q.id],urls=voicevoxUrls(rec);if(!urls.length)return null;return{candidates:urls.map(url=>({url,provider:voicevoxProvider(url),audio:null,objectUrl:null})),out:{...rec,source:"VOICEVOX"}}}
async function candidateAudio(candidate){if(candidate.audio&&candidate.audio.src)return candidate.audio;if(Number.isFinite(candidate.offset)&&Number.isFinite(candidate.size)){const end=candidate.offset+candidate.size-1;const r=await fetch(candidate.url,{headers:{Range:`bytes=${candidate.offset}-${end}`},cache:"force-cache"});if(r.status!==206)throw new Error(`${candidate.provider} 不支援音訊範圍讀取（HTTP ${r.status}）`);const blob=await r.blob();if(blob.size!==candidate.size)throw new Error(`${candidate.provider} 音訊範圍大小不符：${blob.size}/${candidate.size}`);candidate.objectUrl=URL.createObjectURL(new Blob([blob],{type:"audio/mpeg"}));candidate.audio=new Audio(candidate.objectUrl);candidate.audio.preload="auto";return candidate.audio}candidate.audio=new Audio(candidate.url);candidate.audio.preload="auto";return candidate.audio}
function disposeVoicevoxPrepared(prepared=game?.voicevoxPrepared){for(const c of prepared?.candidates||[]){try{c.audio?.pause()}catch{}if(c.objectUrl){try{URL.revokeObjectURL(c.objectUrl)}catch{}c.objectUrl=null}c.audio=null}}
async function playPreparedVoicevox(prepared,rate=1,forSample=false){if(!prepared?.candidates?.length)throw new Error("此音訊沒有可用來源");let lastError=null;for(const candidate of prepared.candidates){let a;try{a=await candidateAudio(candidate);activeAiAudio=a;a.pause();a.currentTime=0;a.playbackRate=rate;await a.play()}catch(e){lastError=e;if(String(e?.name||"").includes("NotAllowed"))return true;if(candidate.objectUrl){try{URL.revokeObjectURL(candidate.objectUrl)}catch{}candidate.objectUrl=null}candidate.audio=null;activeAiAudio=null;continue}const meta=prepared.out||{},who=[meta.speaker,meta.style].filter(Boolean).join("／");if(forSample){$("#sampleVoiceStatus").textContent=`✅ 試聽：${who||"VOICEVOX"} · ${candidate.provider} · ${meta.text||""}`;return true}$("#voicevoxStatus").textContent=candidate.provider==="Hugging Face 備援"?"✅ GitHub 音訊不可用，已自動切換 Hugging Face 備援。":`✅ VOICEVOX 正在使用 ${candidate.provider}。`;unlockAfterPlay(`VOICEVOX${who?" · "+who:""} · ${candidate.provider}`);return true}throw lastError||new Error("所有 VOICEVOX 音訊來源均無法播放")}
async function playVoicevoxRecord(rec,rate=1,forSample=false){const prepared={candidates:voicevoxUrls(rec).map(url=>({url,provider:voicevoxProvider(url),audio:null,objectUrl:null})),out:{...rec,source:"VOICEVOX"}};return playPreparedVoicevox(prepared,rate,forSample)}
async function prepareVoicevoxSetupSample(){if(voicevoxFullIndex){const keys=Object.keys(voicevoxFullIndex.speakers||{});let key=selectedVoicevoxSpeaker();if(key==="random"||!voicevoxFullIndex.speakers?.[key])key=keys[0];const qid=Object.keys(voicevoxFullIndex.questions||{})[0];const prepared=fullPreparedFor(qid,key);if(prepared)return prepared}const name=selectedVoicevoxSpeaker();const rec=Object.values(voicevoxIndex?.items||{}).find(r=>name==="random"||r?.speaker===name);if(!rec)return null;return{candidates:voicevoxUrls(rec).map(url=>({url,provider:voicevoxProvider(url),audio:null,objectUrl:null})),out:{...rec,source:"VOICEVOX"}}}
async function speakVoicevox(rate=1){const st=$("#voicevoxStatus");try{let prepared=game.voicevoxPrepared;if(!prepared&&game.voicevoxPromise)prepared=await game.voicevoxPromise;if(!prepared)prepared=await prepareVoicevoxAudio(game.current);if(!prepared?.candidates?.length)throw new Error("此題尚未有 VOICEVOX 音訊");game.voicevoxPrepared=prepared;return await playPreparedVoicevox(prepared,rate,false)}catch(e){st.textContent="⚠️ GitHub 與 Hugging Face 的 VOICEVOX 音訊暫時都無法播放；已改用其他語音備援。";return false}}'''
s=s[:start]+replacement+s[end:]

old='''if(mode==="voicevox"){const name=selectedVoicevoxSpeaker();const rec=Object.values(voicevoxIndex?.items||{}).find(r=>name==="random"||r?.speaker===name);if(!rec)throw new Error("目前找不到這個 VOICEVOX 聲線的試聽音訊");await playVoicevoxRecord(rec,1,true);return}'''
new='''if(mode==="voicevox"){const prepared=await prepareVoicevoxSetupSample();if(!prepared)throw new Error("目前找不到這個 VOICEVOX 聲線的試聽音訊");await playPreparedVoicevox(prepared,1,true);return}'''
assert old in s
s=s.replace(old,new,1)

old='''game.plays=0;game.lastAudioLabel="";game.voicevoxPrepared=null;game.voicevoxPromise=$("input[name=audioEngine]:checked")?.value==="voicevox"?prepareVoicevoxAudio(q):null;game.aiVoiceForQuestion=null;'''
new='''game.plays=0;game.lastAudioLabel="";disposeVoicevoxPrepared();game.voicevoxPrepared=null;game.voicevoxSpeakerForQuestion=null;game.voicevoxPromise=$("input[name=audioEngine]:checked")?.value==="voicevox"?prepareVoicevoxAudio(q):null;game.aiVoiceForQuestion=null;'''
assert old in s
s=s.replace(old,new,1)

old_text='每個句子目前有一條已預錄 VOICEVOX 音訊。指定聲線時，遊戲會只使用已有該聲線的題目；選「每題使用不同預錄聲線」可使用完整題庫。GitHub Releases 播放失敗時會自動切換 Hugging Face。'
new_text='完整聲線庫完成後，每個可選 VOICEVOX 聲線都會有同一套 3,310 題；可固定一個聲線完成整次練習，或每題隨機。音訊以 GitHub Releases 為主，Hugging Face 為自動備援。建置完成前會安全保留舊版輪替音訊。'
assert old_text in s
s=s.replace(old_text,new_text,1)

p.write_text(s,encoding='utf-8')
print('Patched Listening to v1.9 full-per-speaker VOICEVOX bundle support')
