#!/usr/bin/env python3
"""Merge strict coverage additions into the generated advanced vocabulary bundle.

The main builder intentionally chooses a canonical JMdict writing. This
post-processing step preserves reviewed alternate written forms as independent
learning entries without changing that builder's broad candidate-selection
logic.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEVELS = ("N1", "N2", "N3", "N4", "N5")


def parse_bundle(path: Path):
    text = path.read_text(encoding="utf-8")
    start = text.find("const M=")
    mid = text.find(",T=", start)
    end = text.find(";\nwindow.ADVANCED_WORDS", mid)
    if start < 0 or mid < 0 or end < 0:
        raise RuntimeError(f"cannot parse generated bundle: {path}")
    meta = json.loads(text[start + len("const M="):mid])
    tuples = json.loads(text[mid + 3:end])
    return meta, tuples


def normalize_key(reading: str, word: str) -> str:
    return f"{str(reading or '').strip()}|{str(word or reading or '').strip()}"


def render(meta: dict, tuples: list[list]) -> str:
    payload = json.dumps(tuples, ensure_ascii=False, separators=(",", ":"))
    meta_json = json.dumps(meta, ensure_ascii=False, separators=(",", ":"))
    return (
        "// AUTO-GENERATED by tools/build_vocab_bundle.py + tools/apply_coverage_additions.py. Do not edit by hand.\n"
        "// Advanced learning bands are estimated and are not an official JLPT vocabulary list.\n"
        "(()=>{\"use strict\";\n"
        f"const M={meta_json},T={payload};\n"
        "window.ADVANCED_WORDS=Array.isArray(window.ADVANCED_WORDS)?window.ADVANCED_WORDS:[];\n"
        "const base=window.ADVANCED_WORDS.length;\n"
        "for(let i=0;i<T.length;i++){const x=T[i];window.ADVANCED_WORDS.push({id:`bundle-${i}`,level:x[0],reading:x[1],kanji:x[2]||\"\",displayWord:x[2]||x[1],meaning:x[3],pos:x[4]||\"other\",estimated:true,source:\"進階補充詞（預先整理・推定等級）\"});}\n"
        "window.ADVANCED_WORDS_BUNDLE_META={...M,loadedCount:window.ADVANCED_WORDS.length-base};\n"
        "})();\n"
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--bundle", default="data/advanced_vocab.js")
    p.add_argument("--additions", default="data/coverage_additions.json")
    args = p.parse_args()

    bundle = Path(args.bundle)
    additions_path = Path(args.additions)
    if not bundle.is_absolute():
        bundle = ROOT / bundle
    if not additions_path.is_absolute():
        additions_path = ROOT / additions_path

    meta, tuples = parse_bundle(bundle)
    payload = json.loads(additions_path.read_text(encoding="utf-8"))
    additions = payload.get("additions") or []

    existing = set()
    merged = []
    for row in tuples:
        if not isinstance(row, list) or len(row) < 4:
            continue
        level, reading, written, meaning = row[:4]
        word = str(written or reading or "").strip()
        key = normalize_key(reading, word)
        if key in existing:
            continue
        existing.add(key)
        merged.append(row)

    added = 0
    added_by_level = Counter()
    skipped_existing = 0
    for item in additions:
        level = str(item.get("level") or "N1")
        reading = str(item.get("reading") or "").strip()
        word = str(item.get("word") or "").strip()
        meaning = str(item.get("meaning") or "").strip()
        pos = str(item.get("pos") or "other")
        if not reading or not word or not meaning:
            continue
        key = normalize_key(reading, word)
        if key in existing:
            skipped_existing += 1
            continue
        written = word if word != reading else ""
        merged.append([level, reading, written, meaning, pos])
        existing.add(key)
        added += 1
        added_by_level[level] += 1

    counts = Counter(str(x[0]) for x in merged if isinstance(x, list) and x)
    meta = dict(meta)
    meta["version"] = "prebuilt-20260821-v4-strict-surface-coverage"
    meta["generatedCount"] = len(merged)
    meta["coverageAdditionsRequested"] = len(additions)
    meta["coverageAdditionsApplied"] = added
    meta["coverageAdditionsAlreadyPresent"] = skipped_existing
    meta["coverageAdditionsByLevel"] = {lv: added_by_level.get(lv, 0) for lv in LEVELS}
    meta["countsByLevel"] = {lv: counts.get(lv, 0) for lv in LEVELS}
    meta["coverageRule"] = "Exact written-form + reading pairs are independent; approved alternate writings are preserved."

    bundle.write_text(render(meta, merged), encoding="utf-8")
    print(json.dumps({
        "before": len(tuples),
        "requested": len(additions),
        "applied": added,
        "already_present": skipped_existing,
        "after": len(merged),
        "added_by_level": {lv: added_by_level.get(lv, 0) for lv in LEVELS},
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
